### ISSUE TITLE
Bug: fontäner kommer inte tillbaka

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#100]
Jag har börjat märka att fontäner inte kommer tillbaka, åtminstone så syns de inte på min klient. Det gäller fontäner som borde ha kommit tillbaka inom några dagar...

Fungerar på om vi inte ska sätta en tidpunkt då vi rensar allt och börjar om från början så att vi inte får buggar på grund av gammal data som ligger och skvalpar i databaserna, vad tror du?

**Comment by melker** [comment]
Fixat buggar på sever. Förhoppningsvis är det löst nu.
