### ISSUE TITLE
Ny byggnad: Probe launcher

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#104]
Borde gå att se kartan där man själv inte är just nu. Därför behövs en ny byggnad, en probe launcher.

När man skickar iväg en probe så ska man kunna, under en viss begränsad tid, se den på kartan och se kartan såsom om man stod just där.

Uppgrade path:
# of Probes: startar med 1, bygger vidare med 1.

Recharge time: hur länge från det att man skickar iväg en probe tills den kan användas igen, startar med 2 timmar? (behöver testas) går ned allteftersom (med 1/3 av tiden som man är på just då?)
Probe duration: hur länge proben är ute på kartan, startar med 2 minuter och ökar med 2? 5? minuter per level. Vet inte om det kommer att användas så mycket, vi får se.

**Comment by melker** [comment]
Byggnaden kan nu byggas. 0.4.95
(dock inte uppgraderas eller användas än)

**Comment by melker** [comment]
Jag föreslår, för att göra det teknisk enklare, att vi byter ut number of probles till probe range. Hur långt bort man kan placera den. (Det blir annars bök med att ha koll på återhämtningstid för flera olika probes vilket inte stöds av nuvarande datamodell.)

**Comment by melker** [comment]
0.4.96
Byggnaden kan byggas, och upp- och nedgraderas. (enligt mitt ändrade förslag)

**Comment by filwi** [comment]
Vad hindrar en från att placera massor med probes och bara scanna av hela området som man kan nå? Det skulle i så fall vara exakt samma som att se längre bort i den vanliga vyn förutom att spelaren måste klicka som en galning.

**Comment by melker** [comment]
Va? Du kan bara placera en probe när byggnaden är "uppladdad".

**Comment by filwi** [comment]
Jag uppfattade det att vi ersatte probes med range. Men om man bara kan kolla när den är uppladdad så är det bra. Men då får vi ha en kort laddtid, annars blir det bara tråkigt för spelaren.

Eller så kan man säga att återhämtningstiden börjar när man skickar iväg den första proben, oavsett när man skickar iväg de andra, så som för att bygga workers.

**Comment by melker** [comment]
Nej nej nej. Min tanke:

Number of probes -> probe range

Dvs hur långt från min plats jag kan placera den. (Så man inte kan sätta
den på andra sidan jorden heller)

**Comment by filwi** [comment]
Men man kan fortfarande bara sätta på ett ställe? Dvs, man kan inte "surfa runt" för att hitta något bra ställe att åka till utan bara chansa på att se ett ställe?

**Comment by melker** [comment]
Ja. Jag uppfattade tanken så...

Eller tänkte du att man skulle kunna "surfa runt" under en viss tid? Skulle
också funka... funktionen är ju inte byggd än.

**Comment by melker** [comment]
Vi kan göra det så här:

När man skickar en probe så hämtar klienten information om allt inom [probe range] från den punkt man just nu är på.
Man hamnar i "probe mode":
- man kan fritt scrolla runt på kartan
- man kan INTE interagera med saker på kartan utan bara se dem
- man får en nedräkning på hur långa tid man har kvar (som man kan avbryta i förtid om man vill), [probe duration]
  När den avslutat probe mode (själv eller automatiskt) så måste man vänta innan den laddat upp sig igen. [probing recharge time]

**Comment by melker** [comment]
Till mig själv:
Nu finns det otestad kod på servern... den returnerar saker inom mycket större radie från användaren.
Den borde dock även skicka tillbaka någon markör om att byta till probe mode...

**Comment by melker** [comment]
Släpper ut en första version i 0.4.100
Notera att probe duration inte har någon effekt just nu... och så kanske vi ska ha det?
De andra två har det däremot.

**Comment by melker** [comment]
Efter diskussion idag: 
- När man startar en probe så kör man på som vanligt men ha en stor view range på användaren och en nedräkning på tiden. Allt övrigt är som vanligt. Mna kan klicka och placera etc (men med samma vilkor som vanligt då)
- Dra ner på range 1,2,3,4 etc km. Det blev för långt. Har man väl 2 km så var det inte intressant att utöka mer.
- Placera probe-knappen under "hoppa mellan gates"-knappen.

**Comment by melker** [comment]
0.4.102
När man nu kör en probe så utökar den visible range runt användaren under den specificerade tiden. (1, 2, 3... minuter). Inga andra special-modes eller liknande.

Kvar:
- Dra ner på range 1,2,3,4 etc km. Det blev för långt. Har man väl 2 km så var det inte intressant att utöka mer.
- Placera probe-knappen under "hoppa mellan gates"-knappen.
- Klocka som räknar ner hur långt det är kvar

**Comment by melker** [comment]
0.4.103
- Range justerad till: 1500m, 2000m, 2500m etc (man har ju 1000 ändå)
- Probe-knappen flyttad

Klockan hamnar som rest i eget issue då det är något som strular med den....
