### ISSUE TITLE
Inte tillåta spel utan GPS-låsning

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#109]
Jag blir irriterad över att man har sin GPS pryl på gamla stället när man har flyttat sig. Som jag ser det är det två möjliga lösningar:
1. Vi tillåter inte att man spelar utan GPS-låsning. "You are here" och cirkeln finns helt enkelt inte tills man har fått en GPS låsning.
2. Vi gör två lookups, först en medium accuracy, som tar wifi, teletorn etc., sparar den positionen i var man är, och sedan kör en high accuracy efteråt. Det är inte lika bra men det låter en spela på ungefär rätt position snabbt.

**Comment by melker** [comment]
En av de största saker som stör mig otroligt med Ingress är just att den
måste ha en fix position med någorlunda säkerhet innan man får göra något.
Så vill jag absolut INTE ha det i detta spel.

erik.melkersson@gmail.com

**Comment by filwi** [comment]
Vad sägs om lösning 2 då? Först köra en snabb medium accuracy fix, spara den i current position eller vad det hette, och sedan sätta på GPSn.

Eller finns det något sätt att använda den "stora" fixen och bara ta mitten på den så fort GPSn går igång? Det brukar vara hyffsat tillförlitligt. (Med stora fixen menar jag den stora cirkeln som dyker upp i google maps när man startar den innan den har lyckats dra ned det till en exakt fix.)

**Comment by melker** [comment]
Mja.... man bör nog även kolla på hur gammal "lastknownposition" är. Om den
är mindra än..... säg 5 minuter... så tar den den från GPS-en annars kan
den ta en från meduim accuracy (nätverk etc) eller gps, vilket den än får
först.

Här ute på landet kan jag hamna en halvmil fel om man har medium accuracy,
och den kan hoppa fram och tillbaka i den storleksordningen. Inne i staden
kanske det funkar bättre.

**Comment by melker** [comment]
Min tanke just nu är att:

```
if (gps-en har en pos som är mindre än 5 minuter gammal) {
  Använd den.
  Starta prenumeration på gps-uppdatering.
} else {
  Starta pren på gps
  Starta pren på nätverksplats
  Betrakta det som att vi inte har någon plats än
}
...
onLocationChanged(...) {
  if (vi får pos från gps) {
    sätt att det är den som gäller
    avsluta ev pren på nätverksplats
  } (vi får pos från nätverk) {
    sätt att det är den som gäller
  }
}

```

Hur låter det?

**Comment by filwi** [comment]
Låter som att det skulle funka bra. Tuta och kör!

**Comment by melker** [comment]
0.4.111
Ändrat hur den lyssnar på vilken position man har.
Den använder GPS-ens position om den inte är äldre än 5 minuter. Sedan lyssnar den både på "nätverksposition" och gps-position. Den tar den som kommer först och placerar ut markören, sedna kommer ju fler psoitioner efterhand. Finns det en giltig gps-position som inte är äldre än 5 minuter har den alltid företräde före en nätverksposition.﻿

Testa och se om det är ok.

**Comment by melker** [comment]
Den använder nu för tiden googles standardförlag på hur man kan lyssna på position och jag upplever att den fungerar bra, liksom ett par testanvändare gör. Jag stänger därför detta.
