### ISSUE TITLE
Öka återhämtningsfrekvensen med många spelare

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#110]
Idé: att man kollar på hur många spelare som finns i rutan (nu eller över en viss tid bakåt) när en fontän töms. Sedan delar man laddtiden med antalet spelare. Det gör att om det finns många spelare så blir det självreglerande, fontänerna kommer tillbaka redo att användas snabbare.

**Comment by melker** [comment]
Intressant tanke.... det borde gå att göra något av. Frågan är bara hur man
räknar "antalet spelare". Hur många som placerat en worker? .... och vad
som är "rutan"? Det finns ju en ruta för varje fontän och även för
potentiella där det inte är någon också...

**Comment by filwi** [comment]
Jag tänkte mig den minsta arean (den som vi har 64 x 64 av) som en ruta.
/F

On 2014-08-27 21:35, Erik Melkersson wrote:

> Intressant tanke.... det borde gå att göra något av. Frågan är bara 
> hur man
> räknar "antalet spelare". Hur många som placerat en worker? .... och vad
> som är "rutan"? Det finns ju en ruta för varje fontän och även för
> potentiella där det inte är någon också...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/melker/colorplanet/issues/110#issuecomment-53628024.

## 

Filip Wiltgren
Freelance Writer & Game Designer

+46 (0)73-577 45 91 | filip@wiltgren.com mailto:filip@wiltgren.com
Website http://www.wiltgren.com | Blog 
http://boardgamegeek.com/blog/1183 | LinkedIn 
http://www.linkedin.com/pub/filip-wiltgren/3/b9a/17b

**Comment by melker** [comment]
Implementationsförlag: En tekniskt mycket enklare variant är att vi loggar utplaceringar i form av:

vilken fontän,vilken spelare,tidpunkt

Denna tabell underhålls så alla poster äldre än en vecka(?) rensas.
Återhämtningstiden minskas ju fler spelare som har satt på den protalen under den tidsperioden.

Då "lönar" det sig att låta någon annan ta den portalen först ibland också, elle vara med.

Fotnot: För statistikens skull har jag en annan tabell som loggar vilka portaler man placerat på och hur många gånger, dock ej tidpunkt. För att hlla ner emängden data lite så är jag inne på att gammal data i denna rensas.

**Comment by melker** [comment]
Min ide är redan implementerad.
