### ISSUE TITLE
Workers grafik

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#112]
Varianter som behövs:
- egen worker
- lagets worker
- annat lags worker
- annan spelares worker (som ej är med i något lag)
- okänd spelares worker (som man inte har kontakt med)

**Comment by melker** [comment]
Justerar lite....

På karta: (med pipeline)
- Egen worker (i alla färger)
- Annans worker (i alla färger)
- Fler varianter?

I listan: (bara workern)
- Egen worker ( i alla färger)

erik.melkersson@gmail.com

**Comment by melker** [comment]
0.4.110
Testade att lägga en pipe på befintliga workers i några varianter Lite olika på olika färger.

**Comment by melker** [comment]
Det finns ju bilder och man ka se dem. Ned-prioriterar denna.

**Comment by melker** [comment]
Moved to bitbucket.
