### ISSUE TITLE
Fontäner och workers buggar

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#114]
Med lite testning verkar det som att fontänerna försvinner när de är tomma men de workers som finns på dem åker inte hem utan fortsätter att suga tills de är klara.

**Comment by melker** [comment]
Hittade en bug som nog orsakade detta på servern. Fixade den buggen men det behöver testas nu.

**Comment by melker** [comment]
Hmmm... buggen skulle nog kunna gett även fontäner som är nästan tomma, som jag nämner som möjlig felkälla i #64... testning härnäst.

**Comment by melker** [comment]
Ytterligare fix eftersom det vara fel.
Inväntar att någon worker ska skickas hem...

**Comment by melker** [comment]
Testat. NU fungerar det, till slut.
