### ISSUE TITLE
Bug: när man inte har GPS location och ingen gammal så går inte portalknappen till portalerna

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#115]
Som det låter. Om man inte har GPS locked och inte har en gammal position lagrad (jag startade om telefonen) så kan man inte komma till sina portaler via portalknappen.

Det borde funka så att om man inte har någon position så ska den gå igenom alla ens aktiva portaler i stället. Har man ingen position och inga portaler så bör inte knappen synas alls (eller ett varningsmeddelande om att man inte har position eller portaler).

**Comment by melker** [comment]
Hmmm jag har för mig att det funkade så när jag byggde funktionen... men
något kanske flippar ur i aktuell kod.
Den 4 sep 2014 09:09 skrev "Filip Wiltgren" notifications@github.com:

**Comment by melker** [comment]
Har justerat kod.... kommer i nästa version.

**Comment by melker** [comment]
0.4.100
Testa gärna

**Comment by melker** [comment]
Fix confirmed

**Comment by filwi** [comment]
Verkar funka vad jag kan se. Stänga?
