### ISSUE TITLE
Speeda upp starten?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#116]
Tänkte på det som Daniel sa om att det inte finns något att göra i starten. Vad sägs om att man börjar med några workers och lite färg i ens egen färg? Säg 5-10 L1 workers + 30-50 färg? Det gör att man kan börja bygga extraworkers direkt, kan testa på att uppgradera saker direkt, kan göra massor med saker direkt i starten utan att behöva vänta på att ens workers kommer tillbaka.

Sedan borde man ha en probe från starten också, och möjligtvis en portal med.

**Comment by melker** [comment]
En portal har man redan från start.

**Comment by melker** [comment]
Från samtalet: Det är inte bara i början det är dötid. Det är under hela
spelets gång.

**Comment by melker** [comment]
Jag har ju minskat reload-tiden för spawner till 5 minuter per workers. Det snabbar upp starten.
