### ISSUE TITLE
Möjlig lösning på "slå samman scorer kuber" problemet

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#117]
Vad sägs om följande algoritm för scorers: Poäng = (2^level)-level.

Det funkar inte helt 100 för låga nivåer men blir bra sedan:

1
2
5
12
27
59
122
...

Ja, det blir snabbt mycket men det ska det kanske vara, eller?

Annars får vi inte ihop det med att Level+1 ska vara bättre än 2*Level.

**Comment by melker** [comment]
Mja.... den totalt dominerande faktorn är:
2^n  
För nivå 8-saker: (vilket är fullt realisstiskt, nivå 9 kan nog vara det också)
Om man har dubblare i alla färger (realistiskt) får man då ca 64 tusen poäng.
Har man tripplare i alla (man kan byta till sig...) får man ca 8 miljoner poäng.

Man blir då fullständigt dominerande. Det blir för starkt....
å andra sidan så håller det bara en månad.

**Comment by filwi** [comment]
Jag vet. Men annars ser jag ingen rimlig anledning till att slå samman kuber.

Alternativet är väl att vi styr med tillgången till racks och hur mycket utrymme man har i sin parts storage. Men det blir svårare att balansera.

**Comment by melker** [comment]
2^n ger ju just den önskade effekten att det blir exakt samma poäng vid uppgradering pch något negativt baserat på nivån som gör att den blir mindra för lägre.... jag förstår hur du kom fram till just den formeln. 

Vad är det som dy tycker är fel vid låga nivåer? (att man inte får börbättring från nivå 1 till 2?) I övrigt funkar det ju.

Äh, vi kör på det. :-)

**Comment by melker** [comment]
inlagt på server och i kommande klient.
(är hemma med skadad fot idag)
