### ISSUE TITLE
Ändra ordning på Scorer parts

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#119]
Vore lättare att scanna med först Racks, sedan Transmitters (om vi ska ha dem), sedan Extenders i färgordning och sist kuber i färg och storleksordning (liten till stor i varje färg).

**Comment by filwi** [comment]
Testa att ha en radbrytning mellan färgerna också, borde vara lättare att scrolla än att försöka scanna sig fram.

**Comment by melker** [comment]
Sakerna är nu färguppdelade, 0.4.172 med bryt mellan dem (det behövs sorteras om lite till för bättre översiktighet men...)
