### ISSUE TITLE
Max mängd scorer parts + scorers

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#120]
Ska begränsas till 20(?)
Kan uppgraderas med hjälp av byggnaden. (En fördubbling per uppgradering?)

**Comment by filwi** [comment]
20 känns lite. Jag är mer inne på att vi inte har en begränsning på delar utan att vi kör på begränsat antal racks i stället. Det skulle göra att man måste uppgradera.

**Comment by melker** [comment]
Dvs: skrota den byggnaden alltså?

**Comment by filwi** [comment]
Japp. Har för mig att vi redan pratat igenom det någon gång tidigare. Sedan kan vi ju ha en hard limit, säg några hundra parts, för att inte belasta databasen för mycket. Men det är upp till dig.

Eller vill du väldigt gärna ha en limit på parts med byggnad?

**Comment by melker** [comment]
Nej, ingen sådan för min skull. :-)

**Comment by melker** [comment]
Bortplockad i 0.4.112. (Bara i appen, hade ingen effekt på servern än.)
