### ISSUE TITLE
Ide: Låta användarna döpa ytor

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#123]
Användarna vill kunna påverka spelet på något sätt (jmf skicka in egna protaler/bilder i ingress)

Man skulle kunna låta dem döpa ytor. (de mindre ytorna, kanske även mellannivån)

Jag inser naturligvis problemet med att folk kan skicka in fula ord etc på sina språk men det går nog att lösa på något sätt med att man t.ex. måste ha poäng i en yta för att kunna föreslå ett namn på den och någon form av automatiskt rapporteringsssyetm som kan sköta en omröstning eller så....

**Comment by filwi** [comment]
Ingen bra idé - vi saknar resurserna för att hålla något sådant igång och det skulle räcka med att en person spammar så förstör det för en massa folk.

**Comment by melker** [comment]
Mmmmm... man kan döpa dem för sig själv så man kan få koll på dem. Nu är det omöjligt att få någon koll på dem. Det måste ske på annat sätt... som att scrolla runt på kartan på något vis som diskuterats i #89 
Stänger denna.
