### ISSUE TITLE
Utplacering av worker, visa dialogen även när gratis

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#126]
Dvs dialogen för vilken worker man vill välja.

I detta ingår att man ska kunna sätta en inställning för "Automatic worker select on free placement" (eller vad som nu är tydligt) så den funkar som nu.

Anledning: Nya ska begripa vad som händer och vana ska inte störas av det.

**Comment by filwi** [comment]
Inställningen bör heta: Fast worker placement
Om det inte är iklickat (standard från början) ska det stå "Short-press shows worker placement dialogue"
Om det är iklickat bör det stå "Short-press places lowest level eligeble worker, long-press shows worker placement dialogue."

**Comment by melker** [comment]
Fixat i 0.4.103. Tog en fast text i stället. (den växlar inte)
