### ISSUE TITLE
Bug: kartan börjar hacka när man zoomar ut

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#128]
NÄr man zoomar ut börjar kartan hacka kraftigt, allting står och velar och hänger sig i några sekunder, sedan hackar den till ny position, hänger sig igen. Går att replicera, verkar inte vara något annat än att man zoomat ut.

**Comment by melker** [comment]
Duplikat av #99. På just zooma ut blir det extra tydligt. (under vissa förutsättningar)
