### ISSUE TITLE
Visa alla scoring rutor på kartan.

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#129]
Vore bra om scoring-rutorna alltid var inskrivna på kartan, inte bara där man står eller tittar just då. Man kan markera rutan man tittar på men man bör alltid se alla så man vet var gränserna går.

**Comment by melker** [comment]
Jag har funderat en del på hur man kan få något att göra på kartan. Vi kan nog kombinera det med denna.
- En alltid synlig knapp på kartan för att snabbt växla mellan gathering och scoring på kartan. Detta för att inte kladda ner kartan och dessutom prestanda.
- Gathering är som idag (ev ta bort scoringrutan och ranking). 
- Scoring visar alla rutor (men inte en massa andra saker, worker, fontäner, portaler etc)
- Varje ruta har en färgkodning. Svart för att man inte ha någon placering i den. Vit för att man har placerat men har låg rank och den vita tonar upp mot ens egen färg ju närmare placering 1 man är i den rutan.
- Då kan man "göra möster" och tydligt se sin maktposition och var man bör placera scorer för att täcka hela "sin" yta.
- Det är i Scoring mode som man placerar scorer.
- För att få skrytfaktor kan man tänka sig att man kan se hur mycket någon kontollerar i appen eller via webbgränssnitt genom att se någon annans data eller möjlighet att dela sin karta.

**Comment by melker** [comment]
Detta är påbörjat i senast släppta version

**Comment by melker** [comment]
Lägg utritning av rutor i bakgrundstråd så det inte låser ui.

Not: fixar smooth... men gör det med score areas först. Innan jag ger mig på fontäner.

**Comment by melker** [comment]
Kvar: 
Fixa så det fungerar igen: Markera ytan som är i fokus och uppdatera rank-rutan när man scrollar.

**Comment by melker** [comment]
Rank-rutan uppdateras som den ska igen.

Kvar: Markera rutan som är mitt i... på något bra sätt.

**Comment by melker** [comment]
Jag har tänkt lite på denna igen.
Räcker det inte med att:
- Man visar aktuell ruta (som man är i)
- Man visar rutan mitt i bild (kan sammanfalla med den ovan)
- Man visar alla som man tagit poäng i, med färg på.

Detta gör att man kan zooma ut mer och ändå visa rutor.

**Comment by filwi** [comment]
Det man behöver är veta var gränserna mellan rutorna går. Annars kan man inte veta vart man ska åka för att placera scorer.

Men kunde man inte rita in linjerna i stället? Det är väl ritandet som tar tid, när de väl är där så tar det inte mera tid. Så om man ritar in alla linjer (säg 100 X 100 linjer = 10 000 rutor) så behöver man inte rita in mera, eller?

**Comment by melker** [comment]
Jo, jag övervägde en sådan plan först... men sedan övergav jag den för enkeltheten i nuvarande sätt. Vilken även löste att visa var man fått poäng. Går att fundera på den igen kanske....

Men vad är syftet med att trycka ut alla? Varför är det så intressant att se _alla_ gränser när du skrollat till del av kartan än där du är? Räcker det inte med just den delen du visar, det borde väl var den som är intressant. Den visar ju rutan för det som är mitt i bild. Kanske även de omkring? Skulle det vara tillräckligt?

Linjerna är olika i olika stora rutor. Om du scrollar ut och kollar på världsnivå i någon gräns så ser du att det är olika. 

"Alla linjer", hehe, det är 512x512 på _varje_ stor yta.

**Comment by melker** [comment]
Justering av denna issue:
- Markera "aktiv" yta (dvs den som poängen visas för)
- Kunna visa lista för ytor inom rimligt avstånd alt på alla ytor (laddar on demand)
- Cacha scoring-data fram till nästa poängberäkningstidpunkt (då slängs allt)

**Comment by melker** [comment]
0.4.207
