### ISSUE TITLE
Ska man kunna placera transmitters inom sin radie?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#133]
Jag funderar på om man inte ska kunna placera scorers inom sin radie. Vi har ju konceptet "laid back GPS game" där vi inte ska pusha för att springa runt som en galning utan spela lite när man kan och vill. Att behöva springa runt för scorers är lite udda.

Och så får man en anledning till att ställa ut många scorers (vilket är kul) när man kan kolla flera olika ställen att sätta dem på och välja. Och då spelar man mer och oftare.

**Comment by melker** [comment]
Jag skulle kunna tänka mig att man kan få göra det.... men jag minskar prio.

**Comment by melker** [comment]
Nej. Stänger.
