### ISSUE TITLE
Uppdatera pos

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#136]
Efter min ändring av hur den får pos så uppdateras pos inte efter att den väl fått en pos. (Om man går ur och in igen så är den uppdat). Troligen fel i kollen av om nya pos angivelser ska användas.

**Comment by melker** [comment]
Jag hade vänt på ett villkor så den bara accepterade gamla tider på platsangivelser. :-/
Enkelt åtgärdat. ">" => "<"

**Comment by melker** [comment]
Fixat i 0.4.119

**Comment by filwi** [comment]
Visst är det kul när sådant händer ,)
