### ISSUE TITLE
Text på color mängd för stor

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#140]
Problem sedan ändringen, går inte att se hela texten:
![screenshot_2014-10-14-09-06-31](https://cloud.githubusercontent.com/assets/8066290/4625089/dac551c8-5370-11e4-9b82-2d50eaae26a9.png)

**Comment by melker** [comment]
Version?
Den 14 okt 2014 09:08 skrev "Filip Wiltgren" notifications@github.com:

**Comment by filwi** [comment]
0.4.121

**Comment by melker** [comment]
Fixat i 0.4.122
Beräknar storlek på annat sätt.... och kompenserar för långa tal.
