### ISSUE TITLE
Spara information för fontäner/rutor under längre tid

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#141]
Märker att när jag scrollar runt i utzoomat läge så verkar den tappa bort att den har ritat ut rutorna en gång och ritar om dem när jag scrollar tillbaka. Om man skulle kunna sparat det så skulle det kanske inte behöva ladda så mycket och inte heller rita om. Vad tror du?

**Comment by melker** [comment]
Kort svar: De måste plockas bort för att inte krasha hela appen.

Det finns bibliotek där man kan ställa om så de inte visas i stället... men
jag vet inte hur det går med minnet i dem och det är en hel del jobba att
införa ett sådant så det får avvakta.

erik.melkersson@gmail.com

**Comment by melker** [comment]
För övrigt "ladda" gör den inte när du scrollar runt. Ingen nätverkskommunikation för det. Den ladda allt du får se varje gång du laddar något och så automatgenererar den resten. Däremot så ska den visa det grafisk. Det är vad som tar tid.... tror jag. Jag har ju faktiskt inte testat det.

Det man skulle kunna göra är att bygga upp saker för mer utzoomat för den mångden saker. T.ex. om du zoomar ut så den fortfaranade visar fontäner. (det går segt) Sedan zoomar du in. När du då scrollar runt INOM området som du tidigare had utzoomat till så bygger den inte upp några nya objekt på kartan.

**Comment by filwi** [comment]
Vad skulle hända om vi började bygga upp sådana områden i bakgrunden medan spelaren gör annat? Då skulle man aldrig märka av laggen. Eller vad tror du?

Förresten, ska vi visa alla fontäner där man inte kan se dem ens eller ska vi bara ha en markör för "här har du den här fontäntypen" (dvs huvudtyp för den platsen). Då skulle man inte behöva rita ut så många fontäner, om jag räknat rätt så skulle det skära ned med 19/20-delar eller?

**Comment by melker** [comment]
Mycket intressant tanke. Prestandatänket i mig gillar det. :-)
Har du bra förslag på hur vi ska visa färgen på ett område. Tonat "moln" av
en viss färg?
Vad säger storyn om att det är klungor av viss färg här och där?
Något som passar med det?

**Comment by filwi** [comment]
Färgat moln låter som en bra tanke. Bara man kommer ihåg att slå av det när man ska visa scoring ;)

Vi kan säga att alla fontäner läcker färg, därför kan man se den och harvesta den.

**Comment by melker** [comment]
Det jag var entusiastisk över var "molnen" i stället för skuggade fontäner...

Att rita upp för en större yta än den som visas görs ju i viss mån redan så det kan vi göra mer konsekvent. Dvs vi ritar upp för vår maxutzooming när de ska visas. Är man redan på den zoom-nivån så får man ingen nytta av det.

Lägger även in en referens till #99 eftersom det handlar om ungefär samma saker.

**Comment by melker** [comment]
Grundiden: Bytt upp för en större yta en den som visas är fixad i 0.4.123. Stänger denna. (molnen separat)
