### ISSUE TITLE
Ändra tillbaka till level^2 för Scorers

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#142]
Funkar inte med den här. Bättre att köra Level^2 för hur mycket poäng man får för en scorer.

**Comment by melker** [comment]
Fixat på server. (sitter på tåget t Arlanda)

**Comment by melker** [comment]
Klienten ska fortfarande justeras....

**Comment by melker** [comment]
Fixat i klient... kommer med nästa version.

**Comment by melker** [comment]
Fixat i 0.4.123 som nu är släppt.
