### ISSUE TITLE
Ändra färg för Spelarnamn till svart

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#143]
Svårt att se gula spelare, bättre att ha svart färg för alla namn och sedan eventuellt ha deras färg som en ikon efteråt. Så formatet blir [Team förkortning inom hakparanteser] Namn IKON

**Comment by melker** [comment]
Det går ju att lägga en ljus variant som bakgrundfärg... eller att den tonar in bkgr från en sådan färg till vit/svart.

**Comment by filwi** [comment]
Skulle tro att det blir snyggare med samma färg på alla och en ikon. Vill man ha olika färger så är det snarare färg på laget som är viktigt så att man ser vilket lag som regerar, snarare än vilken färg som regerar.

**Comment by melker** [comment]
Har bytt till ikon plus svart text i 0.4.179... Notera dock att i message-dialogen så borde inte listan visas normalt utan komma upp först vid behov. Dvs när man vill lägga till mottagare i ett meddelande.
