### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#148]
Kunna spela även där man inte har nät men har det inom rimligt avstånd.

Dvs man ska kunna gå runt i turistort och sedan gå in på restaurang/pub och synka. Placera workers och scorers. Workers blir ju då i mån av att de har ngt.

Man måste synka inom viss tid. En timme eller så och det räknas från synktiden och framåt.

**Comment by filwi** [comment]
Varför en timme? Antingen kan man spela offline eller inte. Bättre att man kan spela och när den synkar så kollas det om det går att placera ut. Om så, great, annars åker workers tillbaka med oförrättat värv. Och så börjar man räkna färg från syntaxen, inte offline placeringstiden. 

On 7 November 2014 16:28:43 CET, Erik Melkersson notifications@github.com wrote:

> Kunna spela även där man inte har nät men har det inom rimligt avstånd.
> 
> Dvs man ska kunna gå runt i turistort och sedan gå in på restaurang/pub
> och synka. Placera workers och scorers. Workers blir ju då i mån av att
> de har ngt.
> 
> Man måste synka inom viss tid. En timme eller så och det räknas från
> synktiden och framåt.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/melker/colorplanet/issues/148

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by melker** [comment]
Stryker denna. Inte realistiskt dessvärre.
