### ISSUE TITLE
Uppdrag (Missions -> Objectives)

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#150]
Man får efter hand uppdrag att lösa. Detta kan vara ett sätt att sätta sig in i spelet och senare att behålla några även om rankingen i sig är avlägsen då. 

Senare t.ex dominera X antal rutor (brevid?). Ha poäng i 2, 3, ... stora rutor.

Man kan ha flera uppdrag aktiva.

Man får någon form av bonus. Lite kristaller eller t.es en Rack när man omvandlar sin första worker till scorer parts.

Vad sägs?

**Comment by filwi** [comment]
Idén är bra. Till efter betatesten?

**Comment by melker** [comment]
Olika uppdrag man får en liten bonus på alla och man behöver ej ta den i ordning men den visar bara en eller ett fåtal ej klarade. Man får info inför hur man gör och lite om vad det ger och efter mer specifikt vad det ger.

Bygg en worker (en till i bonus alt färg så man kan bygga en till direkt)

Placera en worker

Uppgradera producer till nivå 2

Transformera färg

Bygg en byggnad så man kan göra en worker i annan färg

Transformera en worker

Placera en portal

Uppgradera en byggnad

Bygg en byggnad som kräver alla färger (specificerad) worker to scorer part transformer

Omvandla en worker till scorer part (bonus ett rack)

Skapa kontakt med en annan spelare

Skicka något till en annan spelare

Sätt ihop en scorer

Placera en scorer

Vara bäst i en liten ruta

Vara bäst i nn små rutor (flera i olika steg)

Vara bäst i en/nn mellan/stor ruta

Kontakt med nn spelare

Vara med i ett lag

Placerat någon annans scorer

**Comment by melker** [comment]
Merge worker

Merge scorer part

**Comment by melker** [comment]
Klienten håller bara en lista på vilka texer som inkommit och möjlighet att se dem.

När det kommer en ny så ska den dialogen komma upp. I den kan man även fälla ut och se gamla och andra aktuella. 

Servern har koll på vilka saker man klaratvav och kollar i samband med att man gör en action och loggar och skickar med ny text tillbaka till klienten.

Notering: man måste kunna visa bilder i texterna och även visa vilka bonusar man får. Kan göras psss när man omvandlar worker t scorer part.

**Comment by melker** [comment]
Jag har nu byggt in missions. Med syfte att lära nya spelare hur man spelar.
Jag har en fungerande logik och har lagt upp 5 missions. (de blir ju lite lustiga för oss som redan har gjort en massa saker, redan innan de är införda)
1. skapa worker
2. placera worker
3. uppgradera producer
4. transformera kristaller
5. bygg en worker transformer
- Det finns info (texter och bilder) som visas före och efter ett mission. 
- Det finns en vy (flaggan just nu) för att se alla man klarat och de nu aktuella (klarade visar både före/efter text, de ej klarade bara före texten)
- Varje mission har ett beroende på ett annat mission som ska vara avklarat innan det visas. (förutom första då). Dvs det kan vara flera missions som beror på ett och samma mission. (men en beroendekedja kan ju också ta slut så det går att hålla en rimlig nivå)
- Man kan klara av ett mission längre ner i kedjan men det händer inget förrän man har klarat det mission som den beror på
- Man får bonusar för missions (kristaller, workers, kan vara annat)

**Comment by melker** [comment]
Det finns "objectives" för de grundläggande stegen för att komma fram till att skicka hem scorers och även dominera ytor.

Det är långt ifrån självinstruerande när man spelar men jag anser ändå denna issue som avklarad. Textändringar och nya missions etc får hamna separat.
