### ISSUE TITLE
Använd https för alla anrop

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#154]
Fixa cert på servern och ändra i adressen

**Comment by gurglet** [comment]
Kan rekommendera startssl.com. Där kan man få gratis cert som funkar i alla mainstream browsers och på Android och iPhone (har inte testat andra OS).

**Comment by melker** [comment]
Jag kan fixa Terena-certifikat på lysator, där servern ligger. LiU har ju
det genom Sunet. Jobbar med personen som kan godkänna på
lysator.liu.se-nivån. Själv har jag bara rätt att godkänna på liu.se-nivån
:-)

Men tack för tipset.

**Comment by melker** [comment]
Cert finns på servern.... ska justera i appen.

**Comment by melker** [comment]
Fixed in coming version.

**Comment by gurglet** [comment]
:shipit:
