### ISSUE TITLE
workers places beside fountain when fast placing

### ISSUE THREAD

**Issue by PeterSkov88** [melker/colorplanet#174]
As showen below, fixed after remap:

https://docs.google.com/file/d/0Byy14aOOUYy9QnNndGNZb0NLYTA/edit?usp=docslist_api

**Comment by melker** [comment]
Händer inte längre.

**Comment by PeterSkov88** [comment]
Provade probe och fick se väldigt lite.

Mvh
  Peter

**Comment by melker** [comment]
Probe borde lagts in som en egen ny bug. Den är i alla fall fixas.
