### ISSUE TITLE
Trådsäkring av updateprocessen på serversidan 

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#18]
Flertrådssäkring av updateprocessen på server… bara en tråd i taget som ska göra en update-process. Alt att den är så stabil att det inte kan blir ett problem.

**Comment by melker** [comment]
Jag tror det har nu blivit ett problem. Ger t.ex. negativa värden på workers....
Behöver tänka igenom detta.....

**Comment by melker** [comment]
Jag har nu lagt en en låsmekanism som hindrar samtidig update av värden. Det borde göra att den inte ska ge negativa värden, Vi får väl avvakta och se...

**Comment by melker** [comment]
Jag har lagt på låsmekanism... som jag lagt möda på att fixa fall så jag kunnat testa om den fungerar som tänkt., men kanske måste jag det.

#118 är kanske relaterad, men jag är inte säker. Det förkommer negativa även efter mitt försök med lås.

**Comment by melker** [comment]
Test av låsmekanism verkar dessvärre ge att den inte funkar....

**Comment by melker** [comment]
Nu kör de MySQL-variant med 5.5 med stöd för foreign keys och transactions, whoho!
Dags att fippla runt i db. Att köra update som en transaction borde lösa det. (Skulle dock kunna ge dubbla meddelanden när en transaktion får avbrytas... fast den borde fallera direkt på första skrivoperationen)

Dags att göra om tabeller.

**Comment by filwi** [comment]
Funkar nix. Kolla 09:11 idag (fredag). Fick fountain has dried out och tre stycken workers med -0.8 Rubinium.

**Comment by melker** [comment]
Öhhhh.... one.com har altså uppgraderat sin databas så att jag KAN använda de saker jag skriver om. Jag har inte gjort det än.

**Comment by melker** [comment]
NU har jag lagt dit en transaktion på update-processen. Detta innebär just nu att i stället för att få en felaktig beräkning så borde någon av de inblandade i samtidiga anrop få ett felmeddelande: "Error syncronizing: nnnn". 
Det vore intressant att se vad nnn blir.

Jag har även lagt dit lite foreign keys men det gör nog bara att vi sparar några mikrosekunder :-)

**Comment by melker** [comment]
Själva updateprocessen borde vara trådsäkrad nu. (andra problem med dried out har eget ärende)
Stänger just detta ärende.
