### ISSUE TITLE
meddelanden i konstig ordning

### ISSUE THREAD

**Issue by PeterSkov88** [melker/colorplanet#182]
![screenshot_2015-01-19-21-32-29](https://cloud.githubusercontent.com/assets/10399121/5807478/fcd914fc-a023-11e4-9fc8-02a5df3625ff.png)

**Comment by melker** [comment]
Är det fortfarande så eller har den återställt sig och visar dem bara en gång?

**Comment by melker** [comment]
Det dyker upp då och då, under tiden man spelar och beror på att två anrop har använt samma tid och både får meddelandena. Bugfix (förhoppningsvis) kommer i nästa version 0.4.192

**Comment by melker** [comment]
Det dyker upp då och då, under tiden man spelar och beror på att två anrop har använt samma tid och både får meddelandena. Bugfix (förhoppningsvis) kommer i nästa version 0.4.192
