### ISSUE TITLE
Många scorerdelar (10+) ger rörigt gul.

### ISSUE THREAD

**Issue by PeterSkov88** [melker/colorplanet#185]
![screenshot_2015-01-25-16-32-54](https://cloud.githubusercontent.com/assets/10399121/5891972/0bfcc40c-a4b0-11e4-8e93-84c46e10fd09.png)
Se 13x den tillhör 5 gul men svårt att se är närmare 4 gul.

**Comment by melker** [comment]
Fixat i kommande.
