### ISSUE TITLE
More objectives

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#186]
There is targets for ruling areas Other types should be available too.

Some ideas:
- Built all facilities
- All facilities at, at least, level N (1,2,3,4...)
- Harvest form the same fountain N times, 30, 100, 300, 1000 (Must be placed at least a certain time or something...)
- Unique fountains harvested from (100, 200, 500, 1000, 2000, ...)
- Number of crystals collected 100, 300, 1000, 3000, 10000, 30000, 100000, 300000, 1000000, 3000000, ...
- Top score at a moment, 100, 200, 500, 1000, 2000, 5000, 1000, ...
- Simultaneous workers placed, 50, 100, 200, 500, ...
- Distance between transmitters/workers?

**Comment by melker** [comment]
- Items transmitted to other players

**Comment by melker** [comment]
Text in app prepared for "All facilities at, at least, level N (1,2,3,4...)"

**Comment by melker** [comment]
Prepared for unique fountains, same fountain and facility level on both app and client.
TODO: connect with right dependency in db and activate code on server in updatestat.php

**Comment by melker** [comment]
Activated.

**Comment by maggu** [comment]
Perhaps received crystals and transferred crystals as well?

**Comment by melker** [comment]
Invite other players

**Comment by melker** [comment]
Ideas not yet implemented:
- Top score at a moment, 100, 200, 500, 1000, 2000, 5000, 1000, ...
- Simultaneous workers placed, 50, 100, 200, 500, ...
- Distance between transmitters/workers?
- Items transmitted to other players
- received crystals and transferred crystals

(Invitations has been implemented too)

**Comment by melker** [comment]
Preparing for top score mission...

**Comment by melker** [comment]
Sum of all time placed transmitters ?

**Comment by melker** [comment]
Top world score is stored
Max simultaneous workers placed is stored

App supports the missions.

TODO:
Add in mission-db
Add check in updatestat on server

**Comment by melker** [comment]
Db and updatestat prepared for top score and sim workers. Awaiting spread of new app version released this morning.

**Comment by melker** [comment]
Released:
- Top world score is stored
- Max simultaneous workers placed is stored

To think about:
- Distance between transmitters/workers?
- Items transmitted to other players
- Received crystals and transferred crystals
- Sum of all time placed transmitters

**Comment by melker** [comment]
Also:
- Number of treasures gathered, (1,3,10,30... or  1,2,5,10,20,50...)

**Comment by melker** [comment]
Preparations for max transmitter level and gathered treasures is in the beta-version of the app.

**Comment by melker** [comment]
Max transmitter level released

**Comment by melker** [comment]
I think some between the "modulate first worker" to build "worker to transmitter parts" would be fine. When you expand to the third and forth color to.

Upgrade worker modulator?....

**Comment by melker** [comment]
Moved to bitbucket, and the rest I skipped.
