### ISSUE TITLE
Spawn worker: nedräkning startar om.

### ISSUE THREAD

**Issue by PeterSkov88** [melker/colorplanet#201]
Jag hade 11 sekunder kvar enligt nedräknaren och valde då att byta mellan kartan och worker tab och såg att tiden minskade, men sedan när den skulle varit 0 så blev den 59 sekunder, så jag fortsatte vänta och det hände igen. När den skulle gått ner till 0 blev den 59 igen.
Dock väntar jag till meddelandet kommer så fungerar det.

**Comment by melker** [comment]
Hittade omedelbart felet. Hade du väntat till slutet en tredje gång hade det blivit dags. Har justerat koden för kkommande versioner.
