### ISSUE TITLE
kan inte skapa transmitter

### ISSUE THREAD

**Issue by PeterSkov88** [melker/colorplanet#205]
Försöker mount transmitter och får felet: Server error: Invalid transmitter part
Men den skapades i alla fall.
Se bilden.
![screenshot_2015-05-01-15-19-14](https://cloud.githubusercontent.com/assets/10399121/7430643/4895330c-f016-11e4-8dd2-1787570249b7.png)

**Comment by melker** [comment]
Jag kan inte återskapa felet...

**Comment by PeterSkov88** [comment]
Uppdaterade till senaste, kollade förut men såg ingen ny version då. Nu
fungerar det.
Den 1 maj 2015 6:36 em skrev "Erik Melkersson" notifications@github.com:

**Comment by melker** [comment]
Aha. Då får man nog det med GET i st f POST. Jag testade ju bara med senaste...

**Comment by melker** [comment]
Hmmm... med det felmeddelandt så borde det vara så att det är en del som inte längre finns och den bygger inget.

Tillåt mig gissa hur det gick till:
Först försökte du montera den men fick att det var nätverksfel. (då skickade den anropet till servern men svaret kom bort)
Sedan försökte du montera den, men då fanns ju inte delarna kvar och då ska du få det meddelandet. (Det kanske borde formuleras annorlunda eftersom det faktiskt kan inträffa under de ovan givna förutsättingarna)
