### ISSUE TITLE
"missbruk" av bygga portaler

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#27]
Eftersom det är gratis att bygga portaler så kan man helt enkelt missbruka det till att öka på sin egen range. Man river en portal och placerar ut den på gränsen av sin range, där man står. Använd den för utplacering och sedan kan man köra vidare.

Alternativa tankar för att komma runt det:
- En mindre kostnad för utplacering
- Man kan inte riva portaler utan de lever hela sin livslängd där de är satta
- Man kan inte riva dem direkt utan det tar en kvart eller något. (Man sätter då helt enkelt dess livslängd till en viss id framåt vid det anropet. Enkelt att fixa!)
## \- Man kan inte omedelbart använda en portal. Den har en uppstartstid?

Vad sägs om att lösa det på samma sätt som för workers? Dvs när man
## bygger en portal så kommer nästa portal inom en viss tid att börja kosta?

Men om du river alla portaler du har varje gång så blir ju alla man bygger
den första.
Eller menar du att man någonstans ska lagra senaste portalbyggnadstid och
hur många som byggs sedan dess, ja. Tja.... jag är inte övertygad om att
det är rätt men det kanske funkar.

**Comment by melker** [comment]
Jag kan tänka mig att släppa detta. Nu tycker jag det känns som en del av spelet. Man kan sitta och fippla ut dem för att optimera sin utplacering.

**Comment by melker** [comment]
Din åsikt?

**Comment by filwi** [comment]
Vi släpper det. Helt OK att använda portaler för att förlänga sin range tycker jag.
