### ISSUE TITLE
Visa vad man får vid en worker->scorerpart transform med bilder

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#32]
Gör en gridview i dialogen och visa upp vad man får med bilder.
2 x [2], 1 x [1] etc

**Comment by filwi** [comment]
Sorry, missade den här.

**Comment by melker** [comment]
Påbörjad.

Till mig själv:
Server: måste nog ha namn-värde par i stället för att det ska bli läsbart med json-biblioteket i appen.
App: Skapa upp objekt med rätt bild etc... så den visas.

**Comment by melker** [comment]
Fixat. Kommer i 0.4.70
