### ISSUE TITLE
Något riktigt dyrt att samla till....

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#38]
Kanske räcker med att vissa saker blir väldigt mycket dyrare på nästa nivå eller så kanske det ska kombineras med #12 skrytsak?

**Comment by melker** [comment]
Worker->scorer-part uppgradering som ger lite bättre utdelning skulle kunna vara väldigt dyr.

**Comment by filwi** [comment]
Vad sägs om att man kan samla till egna logos på workers/annat? Så att man börjar med ett gäng standardlogos och kan samla till att kunna göra custom logos på sina workers? Det påverkar inte spelet men ger skryträttigheter.

**Comment by filwi** [comment]
På samma sätt: custom logos för teams.

Vi behöver tänka igenom hur man bygger logos i spelet, så att man kan bygga custom från vissa bestämda komponenter som vi fördefinierar, annars blir det lätt att folk laddar upp bilder på penisar och annan skit.

**Comment by melker** [comment]
Det finns ju monument... stänger denna oklara issue.
