### ISSUE TITLE
Problem med containers

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#40]
Jag kom på varifrån alla våra problem med att bygga dyra saker etc. kommer: containers. Just nu är containers det enda man bygger. När man väl fått ihop en viss nivå på container så är det trivialt att fixa allting annat - containers är så mycket dyrare och går så mycket långsammare att bygga.

Det är inte rätt. Vi borde ha fiero-moments när man bygger något coolt i sin bas, inte en behållare.

**Comment by filwi** [comment]
Är inte det här redan fixat och borde stängas?

**Comment by melker** [comment]
Jag blev inte klok på vad ärendet var men det var altså att ta bort
begränsningen på containers. Då är det fixad.
