### ISSUE TITLE
Visa kostnad för bygge/uppgrad i appen

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#47]
I appen på de rutorna visa kostnaden. Gärna med grafiska symboler. Kanske finns någon bra unicode-symbol för mass. Då blir det enkelt.

**Comment by filwi** [comment]
Bättre att köra med symbolerna för färgen, dvs det som visas på kartan, följt av en siffra.

Det vore bra att göra samma sak i containers, och visa alla färger även när kostnaden är noll (men då ha dem gråade) så att linjen med kostnader alltid är samma. Det underlättar när man ska kolla vad något kostar snabbt.

**Comment by melker** [comment]
Jag har i 0.4.77 fixat sätt att visa siffra plus bild för kostnader. Syns brevid Bygga worker-knappen och när man ska placera en worker på en portal där det kostar lite. (Nu visar den bara de sorter som kostar något)

**Comment by melker** [comment]
Jag anser denna löst. (Att visa gråade har sina för och nackdelar... tills vidare tycker jag det är bättre att inte visa dem, tills jag blir övertalad/bevisad om något annat :-) )
