### ISSUE TITLE
Runda kostnader till 2 värdesiffror.

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#50]
Bör avrunda kostnader för att det ska bli lättare att se vad det kostar:

Beslut: 2 värdesiffror.  Korrekt avrundning.

**Comment by melker** [comment]
Håller nästan med. Vi skippar 25-steget. Jämna 10tal

**Comment by melker** [comment]
Är nog inne på enklare variant som är konsekvent uppåt...att visa max två värdesiffror eller att när man kommer till 20 på siffran högre så skippas denna siffra.

T.ex. 1234 => 1200
2345 => 2000
2999 => 2000
...

**Comment by filwi** [comment]
Jag lutar mot 2 värdesiffror och avrunda uppåt. Då får vi en avrundning på 10 om det är under 1000 och en avrundning på 100 om det är över 1000, det borde stämma väl överens med hur mycket färg man kommer att ha tillgång till i spelets faser.

**Comment by melker** [comment]
Då lör vi på två värdesiffror och riktig avrundning.

**Comment by melker** [comment]
Har lagt in funktion på servern för det. Klienten ska justeras.

**Comment by melker** [comment]
0.4.78
