### ISSUE TITLE
Tillgång till meny/about utan menyknapp

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#53]
Jag misstänker att about-rutan kommer upp när man trycker på menyknappen (du har pratat om en sådan, men jag har aldrig sett någon). Jag har ingen menyknapp på min telefon, så jag ser aldrig det.

**Comment by melker** [comment]
Jag hade fått för mig att det var en av sakerna som måste finnas på android-fån. 

Då får vi väl ordna en sådan... då flyttas även teamknappen dit.

**Comment by melker** [comment]
Var ska vi ha den då? Ska sista "fliken" vara en "..." i stälket?

**Comment by filwi** [comment]
Skulle kunna funka. Eller så tar man bort kartknappen och flyttar alla andra åt vänster. Men det är kanske en annan issue.

**Comment by melker** [comment]
FIxat i 0.4.68. Lade in en knapp till just nu.
