### ISSUE TITLE
Möjligt att ställa ut worker som man förlorar på?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#54]
Just nu kan man ställa ut workers på portaler som kostar mer än vad man kan få ut av att ladda workern full. Det borde inte vara möjligt tycker jag eftersom man kan råka trycka fel och blir då irriterad. Vad tycker du?

Kontrollfråga om den kostar mer än vad man kan få in från den. Det är en justering enbart i klienten.

**Comment by melker** [comment]
Låter rimligt. Kontrollfråga i alla fall.  Man kan spendera för att få
unika i sin statistik...

**Comment by melker** [comment]
De flesta kör fast place och då måste man aktivt göra två handlingar för att placera så man förlorar på den. Stänger
