### ISSUE TITLE
Skilja på Team namn och förkortning

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#56]
Just nu kan man ha hur långa team namn som helst, vilket är helt OK, men det borde inte visas så långa namn i scoringlistor etc, samtidigt som man borde visa vilket team man tillhör.

Därför föreslår jag att man har en team förkortning som team-ägaren anger och som visar i klamrar framför spelarnamnet i scoringlistor etc. som så:

[Imp] Erik
[TDS] filwi

Längden på förkortningen borde inte vara mer än 6-7 tecken (8-9 tecken tillsammans med klamrarna).

**Comment by melker** [comment]
Låter rimligt.

**Comment by melker** [comment]
Den använder nu abbreviation i stället i individuella scoring-listor. (fixat på server)
