### ISSUE TITLE
När den hittat position så ska den visa det på kartan

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#57]
Hade för mig det fanns ticket för detta men hittar ej sådan.

När den inte har pos först och sedan får pos så visas ej markören/cirkeln på kartan.

**Comment by melker** [comment]
Kanske fixat i min versison.....

**Comment by melker** [comment]
Filip: Kolla upp om det funkar i 0.4.69.

**Comment by filwi** [comment]
Verkar funka. Har inte märkt av det de sista dagarna.
