### ISSUE TITLE
Separata knappar för min pos/portalers pos

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#58]
Jag viöl ha en knapp för gå till min pos och en för att bläddra genom portaler.

**Comment by filwi** [comment]
Varför?
Men i så fall, vad sägs om en "egen pos" knapp i nedre högra hörnet på samma sätt som portalerna är i övre högra?

**Comment by melker** [comment]
Varför: När man rör på sig och telefonen uppdaterar... jag bläddrar runt
och sedan har min telefon plötsligt hittat positionen. Då vill jag hoppa
till den positionen... men då måste jag bläddra en massa.

Om den ligger uppe eller nere spelar nog inge roll för mig. Spontant tänkte
jag mig den tillsammans med portal-bläddringsknappen.

**Comment by filwi** [comment]
Ok, jag får min positon väldigt snabbt. Har snarare problemet att Colors låser till en position som sedan uppdateras och inte uppdaterar den.

**Comment by melker** [comment]
Den tar först den senast kända pos, vilken kan vara ganska fel. Sedan
startar gps jobba... vilket kan ta tid.

**Comment by melker** [comment]
Alternativ tanke för att inte bloat-a. Long press på knappen går till user pos?

**Comment by filwi** [comment]
Låter bra.

**Comment by melker** [comment]
Long press fixat. Kommer i kommande 0.4.124
