### ISSUE TITLE
Scorer screen: Short press ska lägga till en del av det man tryckte på

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#59]
Som det står :)

**Comment by melker** [comment]
Först förstod jag ingenting... men... sedan... aha.... så det går fortare, ja.

**Comment by melker** [comment]
Vi pratade om att generellt ha:
click - perform defual action
longclick - menu

Har "drag" längre något syfte att fylla då?
I t.ex. bygg scorer-vyn så vet jag inte hur man ens ska aktivera den.

I workers-vyn så ser jag ingen uppenbar default action mer än att dra hem workers och det tycker jag inte man ska råka göra av misstag. Att få upp info om workern (capacitet etc) får bli default... men hur ska man där då aktivera drag. Longpress som nu? Blir det verkligen konsekvent?

**Comment by filwi** [comment]
Jag ser inte någon poäng med drag egentligen, förutom att scrolla i menyer/på kartan. Ser du?

**Comment by melker** [comment]
0.4.78
