### ISSUE TITLE
Sätta kostnader

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#6]
Vi behöver sätta oss och bestämma kostnader för allt. Just nu är det mycket som hänger i luften; mina förslag:

Bygga Workers (resettar per tidsenhet):
10\* (workers built - 1) av egen färg
4 \* (workers built - 2) av angränsande färger
2 \* (workers built - 3) av resterande färger

Uppgradera Worker factory:
Uppgradering av workers (lvl 1 vid start av spelet, anger högsta uppgradering av workers):
Floor(Level^1,5) \* 10 egen färg
Floor((Level-1)^1,5) \* 6 angränsande färger
Floor((Level-2)^1,5) \* 4 övriga färger

Färgbyte av workers (lvl 0 vid start, en per färgkombination man vill byta till/från):
(Antal levels av färgbyte + 1) \* 10 av målfärgen
(Totalt antal levels av färgbyte + 1) \* 10 av egen färg

Vad jag menar är att om man kan byta lvl 2 workers från röd till gul och lvl 1 workers från röd till blå så kommer det att kosta (2 + 1 + 1) \* 10 = 40 av egen färg att bygga en lvl 1 röd till grön bytare (eller uppgradera någon av de andra en level). Det gör att det spelar roll vilken färg man själv har - man måste alltid sattsa på att ha mer i sin egen färg, vilket gör att man inte konkurerar med de andra spelarna i ens lag (eftersom vi sagt att man kan bara ha en spelare av varje färg i ett lag).

Uppgradera Portal factory:
Max Antal portaler (startar Lvl1):
Runda till närmsta 5-tal(Lvl^2,2) av alla färger.

Portalernas livslängd (7^(Lvl/antal portaler på kartan) dagars livslängd per protal, startar lvl 1):
Runda till närmsta 5-tal(Lvl^2,9) av alla färger.

Det här gör att det är lättare att bygga fler portaler men svårare att hålla dem vid liv. Det ger incentiv till att röra på sig och åka ut och ställa ut portaler. Vi skulle kunna göra det omvänt, att det är lättare att hålla dem vid liv men att det skulle göra spelet mer stillasittande.

Portalernas räckvidd (lvl ^ , egen räckvid är portalernas + 200 m sa vi tror jag, startar lvl 1):
## Ungarna låter mig inte jobba, fixar sen.

```
Filip Wiltgren

Portalernas räckvidd (föregående levels radie + 100 * 2 ^ (2/ny level)-1). Så om vi startar med 100 m radie så blir radien för lvl 2: 100 m + 100 * 2 ^ (2/2)-1 = 100 + 100 * 1 = 200 m. För lvl 3 blir det 258 meter, för lvl 4 300 m, lvl 5, 332 m osv. Ökningen kommer att fortsätta i all oändlighet men med mindre och mindre marginaler per level.

Kostnad för att öka portalernas räckvidd:
Runda till närmsta 5-tal(Lvl^2,35) av alla färger.

Om man sätter samman dessa två formler så blir den effektiva limiten för hur mycket man kommer att kunna öka sin radie ca 400-450 meter beroende på hur mycket man spelar. Sedan är det ganska så svårt att öka mera.
```

---

```
Erik Melkersson

Försökte just begripa (utan att inse) vad:
- En worker färgbytarbyggnad ska kosta att bygga, lvl 1, och uppradera, lvl 2, 3 etc. (Just nu drar den 10 av färgen man byter från och 10 av den man byter till, 20, 40 etc vid uppgrad.)
- Vad det ska kosta att ändra färg på en worker. (just nu 5 av målfärgen, oavsett level)

Tanke: En lvl X färgbytare kan byta färg på en worker som har level<=X. Låter det bra? (så kommer man inte får så bra workers i andra färger omedelbart utan det blir fler steg som man vill uppgradera)
```

---

```
Filip Wiltgren

Färgbytarbyggnaden har en kostnad som är baserad på två saker, dels leveln på den nivå man ska byta till, dels alla levlar som man har uppgraderat.

Exempel:

Byggnaden kan byta:
Lvl 3 workers från röd till gul (dvs röd till gul är uppgraderad tre gånger tidigare)
Lvl 1 workers från röd till blå
Lvl 0 workers (inga färgbyten) från röd till grön

Kostnad att uppgradera blir då:
Uppgradera röd -> gul till lvl 4 kostar 50 av egen färg (3 lvl röd->gul + 1 lvl röd -> blå + 1 = 5 levels totalt * 10 av egen färg) och 40 av gul (3 lvl röd->gul + 1 = 4 * 10 av målfärgen).
Uppgradera röd -> blå till lvl 2 kostar 50 av egen färg (samma som ovan) och 20 blå
Uppgradera röd -> grön till lvl 1 kostar 50 av egen färg (samma som sovan) och 10 grön

Tanken är att man inte kan stoppa in workers av högre level än vad man kan byta till. Men då behöver man kanske ha en "nedgradera worker" funktion om man verkligen behöver ett visst byte.
```

---

```
    Erik Melkersson

    Gah!
    Jag tror vi pratar förbi varandra.

    Jag har tänkt och redan implementerat så här:

    Man kan bygga en byggnad som
    konverterar från färg X till X+1.
    konverterar från X till X-1.
    det är olika byggnader för varje X.
    Dvs det finns 2(antalet färger) byggnader.

    Varje sådan byggnad får nivå 1 när den byggs och är en förutsättning för
    att man ska kunna konvertera en worker mellan de två färgerna. När den
    uppgraderas får den 2, 3 etc.

    Rent grafisk kommer de visas i samma "byggnad" i gränssnittet under
    facilities.

    För övrigt så trode jag vi var överens om att en worker startar på level 1.
    (1 är den första, vi använder inte 0) ?

    Är du tillbaka och på jobbet?
    Jag kan visa på min telefon....
```

---

```
Erik Melkersson

Efter diskussion idag:
T.ex. att bygga en X->Y transformer ska kosta N av en s egen färg (någon form av grundkostnad) plus M av varje färg som ingår i transformen (X och Y). Samma sak vid uppgradering.

Man kan tänka sig att kostnaden påverkas av hur många transformers det finns sedan tidigare. Nackdelen med det är att man kan bygga upp en transform hög och sedan få det otroligt svårt att få till nästa transform-byggnad. (tror ja... eller blir det inte så då?)
```

---

```
Filip Wiltgren

Namn i "citationstecken" är variabler som måste genereras från spelet, namn i [klamrar] är variabler som sätts genom fil

Bygga workers:
Egen färg: [KostnadEgenFärg] * ("Antal byggda workers denna tidsperiod" + [EgenFärgAntal])
Närliggande färger: [KostnadNärliggande] * ("Antal byggda workers denna tidsperiod" + [NärliggandeAntal])
Återstående färger: [KostnadÅterstående] * ("Antal byggda workers denna tidsperiod" + [ÅterståendeAntal])

Filen blir då:
KostnadEgenFärg;EgenFärgAntal;KostnadNärliggande;NärliggandeAntal;KostnadÅterstående;ÅterståendeAntal

Låter det vettigt som sätt att formattera?
```

---

```
    Erik Melkersson

    Formlerna får du specificera på det viset men syntaxen i filen är namn/värde-par.

    Dvs något i stil med:

    KostnadEgenFärg=10
    EgenFärgAntal=2

    Fast det är bättre med engelska variabelnamn som dessutom är lite mer kompletta så man får sammanhanget.

    worker-build-mycolor-base=10
    worker-build-mycolor-built=2
    worker-build-nearcolor-base=0
    worker-build-nearcolor-built=2
    ...

    Om det sedan är streck eller camelcase spelar ingen roll. Bara bestäm något.

    I just den formeln ska det väl vara med en thrshold för för de är i effekt också.
```

**Comment by melker** [comment]
Har mixtrat med byggnaders kostnad, för bygge och uppgradering, på serversian:
Har just nu satt uppgraderingskostnader till: (utgår från befintlig level)
10_e^(level) i byggnadens färg
4_e^(level-1) i närliggande
1*e^(level-2) i övriga färger
Om byggnaden inte har färg så använd spelarens färg.

Detta gör att det sticker iväg i pris efter några nivåer...

**Comment by melker** [comment]
Är det något av det här som höver fixas fortfarande?

Jag föreslår att vi tills vidare hårdkodar kostnader i både app/server för att komma vidare.... och skjuter punkten att kunna justera direkt lite på framtiden. Högre milestone.

Vi fortsätter använda modellen

Nmine_e^(level)
Nnear_e^(level-1)
Nother*e^(level-2)

För saker som ska sticka iväg i pris. T.ex. byggnader.

**Comment by melker** [comment]
Har du något mer att säga här eller kan vi släppa denna issue? (är lite rörig och inaktuell också....)

**Comment by filwi** [comment]
Vi släpper den så länge. Kör på med viktigare saker så ställer vi in kostnader när vi har grunden färdig; funkar ju ok nu.
