### ISSUE TITLE
Ska vi tillåta att man kombinerar scorer parts till bättre parts?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#61]
Det skulle även kunna innebära att vi har en "part improvement" byggnad vars level styr vilken level på parts man kan kombinera. Jag tänker mig 2-till-1-bättre men det kan behövas 3-till-1 eller mer beroende på hur vi ställer algoritmen för att få prylar.

Just nu är allt ungefär lika bra, men när vi har en begränsning på hur mycket man kan ladda in i en rack så kommer ettorna att vara verkligt kassa jämfört med andra (särskilt som man redan får level^2 i poäng, vilket är bra).

**Comment by melker** [comment]
Det är väl då en "extension" kommer in bra. Dvs att kunna lägga på fler saker.

**Comment by filwi** [comment]
I så fall måste extensions vara ganska så vanliga för annars har man ändå ingen användning av 1 containers - man måste ha så hiskeligt många för att det ska funka.

Alternativet är att man har en "snabbygga-knapp" som slänger ihop en scorer av de kassaste delarna man har, men då är det inte lika kul att samla delar och bygga mastiga scorers (vilket är det roliga).

Annars kommer man bara ha en massa knapptryckande utan egentligt resultat för att bygga skräp-scorers (1 poängs scorers). Och sedan ännu mer knapptryckande för att sätta ut dem. Bättre att man har scorers som man säger "wow, vilken grej" när man bygger/använder, dvs scorers som ger spelaren en känsla av makt i stället för grinding; vi har redan grinding genom att man måste samla färg och bygga gubbar.

**Comment by melker** [comment]
Man kan ju i grundutförandet tillåta att man kan ha en eller två extra. (för att fylla upp till rätt nivå). Då kan man slänga med en etta eller tvåa för att få upp färgerna till samma nivå.

**Comment by melker** [comment]
Se #71
