### ISSUE TITLE
Statistics & Medals

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#62]
Lite idéer till sådant som man kan hålla reda på och ge medaljer för:
- max # workers
- max # worker levels (sammanlagt för alla workers)
- max worker level (bästa workern)
- # transformed workers (till andra färger)
- # workers -> scorer parts
- # scorers placed
- max scorer level som man placerat
- # other people's scorers placed
- # of fountains som man satt workers på
- # portals deployed
- # gånger man tittat i appen
- # of timmar man spelat
- max score
- best placering (bigarea - per bigarea, world)
- best placering (i en ruta, spelar ingen roll vilken ruta)

Vad tror du?

**Comment by melker** [comment]
Se #8

**Comment by melker** [comment]
Flyttade kommentarer till 8
