### ISSUE TITLE
Back-knappen buggar

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#63]
Jag använder back-knappen för att gå ut till kartan men den går tillbaka till en gammal vy i stället, t.ex. från kartan till en worker vy. Ofta visar den inaktuella vyer, fel antal lediga workers, fel aktiva portaler etc.

**Comment by melker** [comment]
Jag har också noterat att den ibland har 2 instanser av kartan igång. .
Tror det är relaterat. Har nog något att göra med hur man startar appen...
om du hittar ett återskapningbart fall får du gärna skriva ner det.

**Comment by melker** [comment]
Undersök närmare: 
http://stackoverflow.com/questions/4341600/how-to-prevent-multiple-instances-of-an-activity-when-it-is-launched-with-differ

**Comment by filwi** [comment]
android:launchMode="singleTask" verkar var rätt lösning, det säkerställer att man alltid hamnar på kartan när man går in i appen, vilket är vad vi vill. Sedan ska back-knappen alltid landa på kartan, oavsett vad man har gjort i appen tidigare. Back-knappen från kartan går ut ur appen.

**Comment by melker** [comment]
Har tryckt dit 
android:launchMode="singleTask"
i kommande 0.4.69. Får se om det löser problemen.

**Comment by melker** [comment]
Filip: Kolla upp hur den beter sig i 0.4.69. Om det är ok för dig.

**Comment by filwi** [comment]
Verkar funka, jag kan inte återskapa felet längre.
