### ISSUE TITLE
Fountain has dried up?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#64]
Ibland när jag placerar en worker säger spelet "fountain has dried up" och fontänen, plus alla workers, försvinner från kartvyn. Workersen funkar bra fortfarande, de suger färg etc. men fontänen är ingenstans att se. Vad är detta?

**Comment by melker** [comment]
Fixat buggar på sever. Förhoppningsvis är det löst nu.

**Comment by filwi** [comment]
Nopes finns fortfarande kvar. Inte lika vanligt dock, två gånger på sista veckan.

**Comment by melker** [comment]
Om du lyckas placera en precis efter att den tagit slut så ska du få det.
Men de bör vara ovanliga.

**Comment by filwi** [comment]
Det måste vara något med i vilken ordning som vi kollar om workers placeras och om fontänen ska visas. Situationen just nu:

Fonten är synlig och tom (inga workers på den). Jag placerar workers. Efter någon/några workers så säger fontänen "fountain has dried out" och försvinner. De har inte gått någon tid än, så mina workers har inte börjat suga ur fontänen. De utplacerade workers visas som tomma i worker dialogen. Om jag tar hem dem (genom worker dialogen) så ger de ingen färg. Ändå har de på något sätt sugit slut på fontänen.

Vidare: fontänen försvinner men workers står kvar på den. De suger sig fulla i worker dialogen, sedan kommer de hem som fulla. Det är något som är riktigt problematiskt där och hänger samman med hur vi hanterar workers/fontäner serverside skulle jag gissa.

Behöver du en bättre beskrivning på problemet så kan vi ta det live, säg till.

**Comment by melker** [comment]
Jag funderar på om det på något sätt kan bli så att den bara får extremt lite kvar i fontänen... på något sätt som antagligen är fel. Då beter den sig rätt närman börjar placera ut, för då spelar de sekundrarna roll för att "suga ur det sista".

**Comment by melker** [comment]
Hittar dock inga i databasen med extremt lite kvar...

**Comment by melker** [comment]
Nu är #114 löst och jag vill se hur den beter sig efter det. Det kan ju fortfarande inträffa men det bör vara extremt ovanligt.

**Comment by melker** [comment]
Hittade en annan spännade bug som jag förhoppningsvis justerat nu.
- Om någon vid tid A hade placerat en (eller flera) worker(s) på en fontän.
- Vid tid B placerar spelaren ut en worker. Då beräknas åtgången på fontänen från tid A för ALLA workers. (Vilket kan betyda att den säger att den är slut nu eller nyss, vilket även kan ge ett negativt värde på workers)
- Vid tid B+aningen till ska placera ut en till så har ju fontänen tagit slut med lustiga resultat.

Denna optimeringsmiss kan nog ha ställt till det.

Vi får se om vi slipper dessa saker nu. (Visserligen kan man ju få Fountain has dried upp om man sätter precis när den håller på att faktiskt ta få slut, men extrem udda)

**Comment by melker** [comment]
Har du fått detta fortsatt ganska ofta eller är det ovanligt att det dyker upp (vilket är korrekt)?

**Comment by filwi** [comment]
Ovanligt, stänger detta. Vi får öppna om det återkommer.

**Comment by filwi** [comment]
Nopes, får det igen och på fontäner där ingen annan kan ha tagit ifrån.

Workers står inte kvar på en dried out fontän dock.

Lägg till lite info till felmeddelandet såsom fontännummer, fontänstatus, fyllnadsgrad, vad vet jag, så kan jag skriva med det i buggrapporten så kanske vi kommer fram till vad det är som händer.

**Comment by filwi** [comment]
Förresten, kan det vara att klienten inte har uppdaterad information trots att den borde ha det? Kan man testa det på något sätt?

**Comment by melker** [comment]
Nu kommer den dumpa ut info om fontänens egenskaper innan uppräkning och placering och även lite efter.... så får vi se vad jag kan dra för slutsatser av det.

Notera även om det var på "första" placeringen, "andra" eller kanske på tredje/fjärde.

**Comment by filwi** [comment]
Verkar funka bra nu, har inte fått upp det på över en vecka. Stänger.
