### ISSUE TITLE
Transmitter mounting is reset

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#65]
Just nu nollställs scorern när man byter skärm eller byter fokus bort från appen (släcker skärmen, gör något annat etc.). Den borde vara kvar som den var och det borde finnas en knapp för att nollställa scorer: "reset" i samma vy som "mount".

**Comment by melker** [comment]
Notering: Reset finns redan, fast inte helt självklar.... om man klickar på rack-et som är först så tar man bort allt.

**Comment by melker** [comment]
Moved to bitbucket.
