### ISSUE TITLE
Transmitter parts ideas

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#66]
Förslag: Varje rack har en ruta för varje färg (dvs 5 rutor). Fyller man en ruta med en färg så kan man inte lägga till den färgen igen.

Rack expanders ger extra rutor av en viss färg (de kommer i färger och levels, dvs hur många rutor extra de ger).

Transmitter calibrators: kommer i levels, där höger levels ger extra poäng eller en multiplier på scorern man bygger.

Allt detta för att det ska löna sig att samla på sig delar (kanske byta om vi vill tillåta det) för att sedan göra en jättescorer, dvs något att samla till även på scorer sidan.

**Comment by melker** [comment]
Har preppat appen för procent-bunusar och en mixer.
Har även fixat beräkning i appen,

Nästa steg:
- Lägg in objekten i serverns konstanter
- Fixa beräkning på server
- Släpp ut dem i skatter (minska något annat där) (i 10-50%s varianter)

Avsluta därefter detta ärende.

**Comment by melker** [comment]
Fixat på server.

Kvar:
- Släpp ut dem i skatter och annat
