### ISSUE TITLE
Max worker rest tid: 6 timmar

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#67]
Det borde finnas en cap på hur mycket man måste vänta för att resetta workers klockan. Detta eftersom man måste bränna workers och om man har oändligt med tid inte kan bygga upp en bas till mer än vad man själv + 2-3 portaler kan hålla igång hela tiden. Vi vill ju att folk ska röra på sig lite trots allt.

Jag föreslår en cap på 6 timmar. Har man mindre än 24 workers så minskar den (funkar som idag) men har man mer än 24 workers så resettar worker build klockan efter 6 timmar ändå.

**Comment by melker** [comment]
(1 + bef antal workers) \* 15 minuter men max 6 timmar.
Infört på servern.
