### ISSUE TITLE
Transmitter mounting

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#68]
- Börja bygga scorer genom att lägga in en rack (alternativ, när man byggt färdigt en scorer får man alltid en tom rack om man har en).
- Varje rack har 5 rutor, en för varje färg.
- Det finns en item som heter rack-expander som ger en X nya rutor i en färg. Expanders är färgberoende (dvs har man en röd expander funkar den bara för röda kuber). Man kan inte expandera en expander.
- Det finns olika levels på transmitters, där man får extra poäng (antingen fast summa eller en multiplikator) för högre levels (vad sägs om poäng \* (1+0.1*level))?
- Man kan bygga en byggnad som låter en kombinera två likadana scorer färgkuber till en bättre. Leveln på byggnaden bestämmer vilken level man kan kombinera ihop (så lvl 1 byggnad innebär att man kan kombinera två lvl 1 kuber till en lvl 2 kub).

**Comment by melker** [comment]
Tanke om hur det grafiskt kan funka:

[Rack] [Ext1] [Ext2] [ => ScL]
[C1]  [C2]  [C3]  [C4]  [C5]
[C1e] [C2e] [C3e] [C4e] [C5e]
[C1e] [C2e] [C3e] [C4e] [C5e]

Initialt: Visar en "inaktiv" rack och en inaktiv "=> ScL"-knapp.

Rack: Olika storlek, kan tillåta 0-2 rare-saker (Ext). Rutorna visas när man har en sådan rack.

Transmitter är i stället en "rare"-sak, inget man måste ha.

Knappen för att bygga visar vad man bygger med ikon och level. (Eller är inaktiv när man inte kan bygga)

Cn Visas när man har en rack och är en i varje färg. Om man lägger en expander i dem visas det antalet e-rutor,  2 eller 3(ovanligt).

Åsikter?
Listan med lösa saker bör sorteras på något bra sätt också....

**Comment by filwi** [comment]
Ser bra ut, med ett par ändringar:

tror inte att racken ska vara det som begärnsar hur många rares man kan lägga in, det kommer bara att bli förvirrande att hålla reda på alla racks. Vi låter begränsningen finnas i hur många extenders och transmitters man har.

Färgrutorna ser bra ut, dock: extender rutorna bör vara mindre än den "vanliga" färgrutan för att markera att man inte kan lägga in en extender innuti en annan extender.

Man kanske ska ha en transmitterruta till höger om färgrutorna, i samman nivå som standardfärgrutorna?

Hur vi ska lägga upp lagringen: jag tror på att vi har varje färg på en egen rad, med siffran under färgboxen, vad tror du?

**Comment by melker** [comment]
Till viss del fixat i 0.4.71

**Comment by melker** [comment]
0.4.72 har stöd för 2 och 3-extenders. (fast färgen på dess bild är oftast fel.. har bara gjort en bild)

**Comment by melker** [comment]
Tillräckligt bra för 0.4-nivån. (Förutom bilder då)
Merge kommer men har inte lika hög prio.

**Comment by melker** [comment]
Merge fixat. Inklusive byggnadsberoende.

**Comment by melker** [comment]
Avslutar denna. Inför nya issues om det finns specifika saker som ska fixat med transmitter mounting.
