### ISSUE TITLE
Trading

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#69]
Man ska kunna skicka följande till andra:
- Scorers att sätta ut (måste markera att man har andras scorers på något sätt).
- Färg
- Scorer parts

**Comment by melker** [comment]
0.4.92
Färg - fullt stöd.
Scorer parts och Scorers stöds i appen men inte på servern än.

**Comment by melker** [comment]
Jag är inne på att vi har en tradingbyggnad som tänkt.

Denna styr hur ofta (och kanske hur mycket) man kan skicka något, och om man har en högre level så är "recharge"-tiden kortare. (Man kan skicka en viss mängd av EN sorts färg, eller EN scorer part, eller EN scorer)

T.ex börja på 12 timmar och halvera vid varje uppgradering. 

Om spärr på hur mycket så är det på färgmängd jag kan tänka mig en begränsning. Tex. 10, 20, 40, 80, 160, 320, ...

**Comment by melker** [comment]
0.4.93
Stöd för scorer part och även för scorers inklusive hantering av dem.

Kvar: Kontroll att man har byggnad och tidsgränser på att skicka saker.

**Comment by melker** [comment]
Tidsgräns fixat på serversida. Anser tillräckligt just nu....
Ytterligare features på detta lägger vi på eget ärende.
