### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#7]
Funderar lite på teams

1.När man är med i ett lag, hur ska poängen räknas?

A Hela lagets poäng i area/bigarea/world summeras och laget få EN bonus på det. Dvs man summerar ihop dem bara precis som om hela laget vore en spelare.

B De summeras individuellt och även bonus individuellt för area/bigarea/world, sedan summeras laget ihop.

För/nackdelar:

A blir begripligt att presentera i poänglistan medan jag i dagsläget inte vet hur man skulle presentera B, för det blir omständigt och obegripligt.

A ger ingen bonus för att man placerar andra lagmedlemmars scorers i en yta medan B skulle göra det.

A är nog teknisk enklare att lösa.
1. Var går men med/ur lag? MIn tanke är att under Score-tabben längst ner(?) visa en Team-knapp eller liknande. Under den får man upp en meny med alternativen:
   (
   Start Team
   Join Team
   eller
   Accept Pending Member X (om någon ansökt, alla i laget måste godkänna)
   Reject Pending Member X (om någon ansökt, blir reject om minst en säger det)
   Kick member X (visas först om X varit inaktiv under period N, alla aktiva i laget måste kicka för att någon ska bli kickad)
   Leave Team NN
   )

Under Join Team får man upp lista på de Teams som man har kontakt med någon i och som inte har någon i min färg. (Listar även vilka som är medlemmar i dem)

Start Team - Ange namn och kanske en beskrivning?
1. För att man inte ska kunna växla hur som helt så behövs en fördröjning någonstans... om man lämnar ett lag så får man inte gå med i ett annat förrän om 24 timmar. (Om man blir kickad behöver man inte vänta?)

**Comment by melker** [comment]
Klipper från sourceforge:
- Bilda lag med andra spelare i andra färger. Beräkna ihop poängen.
- En spelare startar laget och döper det. Fler kan ansluta och blir då likvärdiga medlemmar.
- Ingen kan uteslutas såvida inte en spelare varit inaktiv under tidsperiod X och alla övriga i laget är eniga.
- Man kan själv gå ur ett lag.
- När man är med i ett lag så är det laget som får alla poäng. (Dvs lämnar du ett lag får du inga historiska poäng med dig)

Det intressanta med det var den sista punkten:
Dvs alla poäng man skickar sparas på laget och tappar därmed kopplingen till användaren, eller i alla fall beräkningsmässigt även om vi teknisk nog bör spara en pekare. Det gör det enklare att beräkna och gör att vi kan ta bort tidsgränsen för hur snabbt man får byta ett lag. Man får ju ändå inte med några poäng.

Den stödjer även A-varianten av lagpoäng.

**Comment by melker** [comment]
Filip:
Vad tror du om detta: När någon i laget scorar så scorar alla andra i laget en viss procent av den poängen i samma area (och då bigarea/world också). Så vi hanterar inte lagen som entities, bara som bonusar till spelare (och talar om att de har fått en "team bonus" i deras meddelanderuta).

**Comment by melker** [comment]
Skulle kunna funka med lite tankearbete:
Om spelare X1 skickar en scorer i en ruta så:
Får X1 lite poäng medan lagmedlemmar X2 och X3 få, säg 10% av det i den rutan. Ska de då få bonus för sin extra poäng... ? Ska X1 få mer bonus för att X2 och X3 har poäng men lägre i den rutan?
Laget kommer då bara "synas" för lagmedlemmarna själva.  Det blir individuellt spel fortfarande, men man "slipper" hjälpa andra att sätt ut deras scorers (för att själv få bonus) - Vilket jag inte anser önskvärt...

Hmmm... mer fundering.

**Comment by melker** [comment]
Man får ingen motivation att ställa ut andra i sitts lags spelare om de räknas som en spelare heller å andra sidan...

**Comment by filwi** [comment]
Vad sägs om att lösa det på andra sätt? T.ex. att man har en "gemensam" parts byggnad så att om någon skickar in något i den så finns det en liten chans att man själv får ut något av det?

**Comment by filwi** [comment]
Fast vi kanske ska ta ett steg tillbaka: vad vill vi få ut av teams?
1. Social interaktion - att man kan dra med sig andra i sitt lag och hjälpa dem etc.
2. Annat?

**Comment by melker** [comment]
Precis: Det är samarbete och social interaktion. Man vill kanske diskutera/synronisera.
Fast det vill vi ju även utanför lag, men där har vi utbyte av scorers (som ger bättre poäng för alla inblandade) som motivation.

Behövs lag?

Lag kan påverka annan del av spelet, insamling och omvandlning till scorer parts.... jag att bygga något tillsammans kan vara en sak. Man kanske måste "bygga" ihop laget? (en färg påbörjar ett bygga på marken och andra kan fortsätta så man får ihop alla, då har man ett "lag".... eller något som ger någon form av bonus. (Jättekälla till färg som håller lite längre?)

**Comment by filwi** [comment]
Vad sägs om detta: man får automatiskt sitt lags namn innan sitt eget så: [Lag1] filwi
Det kommer att ge en motivation till folk att visa upp sitt lag. Men frågan är då om begränsningen av att man kan bara ha 1 av varje färg i laget är så smart - får att få skryträttigheter behöver man ha stora lag som är kända världen över.

Man skulle även kunna göra en separat scoringlista för lag. Funkar exakt samma sätt som för vanliga personer men det är endast laget som räknas. Har man inget lag så ger man ingen effekt på den listan. Har man ett lag så genererar man sin poäng till rutan för individ-scoring och samma poäng till rutan för lag-scoring.

**Comment by melker** [comment]
Gillar idęn m allianser och namnet brevid.

**Comment by melker** [comment]
... och sep lista för scoring.

**Comment by melker** [comment]
Påståenden:
- Att grunda en allians kostar.... 1000 av egna färgen. 
- för att gå med i en allians krävs en inbjudan alt. Godkännande av EN befintlig medlem. Man måsre ha kontakt med mågon i alliansen. Inga spärrar för färg.
- när man är med kan man skicka meddelande till alla i alliansen (går man ur så är det bara de man faktiskt själv fixat kontakt med.

**Comment by melker** [comment]
Grundaren av alliansen behåller kpntroll av den. Dvs kan kicka folk och döpa om den.

**Comment by filwi** [comment]
Och att man kan dela kontroll, dvs att man kan ge vissa "allians-admin" rättigheter till andra, upphöja dem i status etc.

Ska man ha vissa nivåer i allianser? Typ fasta nivåer som vi namnger som har vissa behörigheter etc.? Fast det kanske kan växa fram allteftersom vi testar.

**Comment by melker** [comment]
Man kan nu skapa ett team (om man har 1000)

**Comment by melker** [comment]
Team scores visas i listorna

**Comment by melker** [comment]
Går nu att bjuda in till ett lag. (Men inte svara än :-)

**Comment by melker** [comment]
Går att svara, både ja och nej, och man kan lämna ett lag.

**Comment by melker** [comment]
Jag har fått igång funktionerna för laghantering. Det som behövs härnäst enligt mig är lite design...

Status i lag känns som ett senare problem.

Jag funderar på om 1000 är för lite. Jag kan dra ihop det på ett par dagar. (har just nu 30 röda workers som i snitt drar ihop 10 per worker)

**Comment by melker** [comment]
Lagnamnet visas efter namnet i vanliga listan med.

**Comment by melker** [comment]
Teamsknappen flyttad och ligger sedan 0.4.77 i övrigt menyn.

**Comment by melker** [comment]
Todo: 
Facility - "Team Headquarter". Krävs för att grunda lag.
Level på den byggnaden avgör hur många man kan ha med i laget (förutom sig själv)

Bara grundaren kan bjuda in folk.

**Comment by melker** [comment]
I team-dialogen ska man få se:

Om man är med i ett lag:
- Namn och vilka som är med
- Möjlighet att gå ur laget (om man inte är grundare)

Om man är grundare till laget man är med i:
- Döp om, namn och förkortning
- Bjud in ny (om man har plats för det). Ska man kunna bjuda in fler än vad som finns platser? (De som svarar ja först kommer med...?)
- Kicka befinlig medlem (med extra kontrollfråga)
- Lägga ner laget (om man vill gå med i någon annans lag t.ex.)

Om man inte är med i något lag:
- Grunda ett nytt lag (om man har byggt den)

Alltid:
- Lista inbjudningar till lag.

Något att tillägga?

**Comment by melker** [comment]
Man kan nu bygga team headquarter (men inte mer). 0.4.95

**Comment by melker** [comment]
Beslut: Kör på enl min senaste notering.

**Comment by melker** [comment]
0.4.108
Påbörjat.

**Comment by melker** [comment]
Fixat även Kick member.

Kvar: 
- Create team (Den som finns funkar men det ska finnas även abbreviation och den ska kolla att namnet och abbr är unikt)
- Edit team (samma koll som i skapa)
- Disband team
- Inte visa inbjudningsknappen eller inaktivera om man har maxantal, visa förklarande text då i stället. Eller visa den texten när man klickar och att den kollar då... vilket som är enklast.

**Comment by melker** [comment]
Create/Edit/Dispand fixade.

Kvar:
Create/Edit - ska kolla krockande namn (server)
Accept ska kolla så det finns platser kvar. (server)
Lågprio:
Invite ska kolla så det finns platser kvar. (klient)

**Comment by melker** [comment]
Klientdelar släppta i 0.4.109

**Comment by melker** [comment]
Fixat på server. Stänger denna.
