### ISSUE TITLE
UI för byta färg

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#70]
![ui modulate color v0 1 140726](https://cloud.githubusercontent.com/assets/8066290/3711949/ac450368-14f3-11e4-93b9-c9665ee5ca10.jpg)

**Comment by melker** [comment]
Vad avses? När man vill ändra färg på bef färg? Den som bara har 10-30? Siffran behöver justeras för hur man väljer i alla fall.

**Comment by filwi** [comment]
Exakt den som säger 10-30 idag.

En draw i mitten och så visar den hur mycket färg man moddar. När man klickar + och - så är det i färgen man moddar från som skiftar (och linjen är färgen man moddar ifrån också).

Man skulle kunna tänka sig att man visar hur mycket av varje färg man har också (så en siffra under mod up och mod down, samt en etta längst till vänster på drag-skalan och hur mycket i färgen man har just nu längst till höger).

**Comment by filwi** [comment]
Mängden färg som man moddar till är avrundat till närmsta heltal.

**Comment by melker** [comment]
Ser vettigt ut men jag kommer använda den färdiga slidern. Tror inte den
har +-10 men man kan ju dra i reglaget då.

Lite färg på up/down med dess symbol. Dvs visa det i stället för texten
up/down.

**Comment by melker** [comment]
Det är kvar i två steg och det behövs en bättre plus/minus-bild men fungerar nu i 0.4.74

Motsvaranda funktionalitet kommer ju även behövas för att skicka till en annan spelare. Då väljer man färg, Skicka, Vilken spelare och sedan Mängd (som använder samma dialog). (Dvs välja spelare blir det extra steget)
