### ISSUE TITLE
Synkronisera i bakgrunden

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#72]
Borde vara möjligt att markera att en action inte är syncroniserad (t.ex. genom att man blinkar en nyligen utsatt worker) och låta spelaren utföra fler actions medan syncen går i bakgrunden. Om syncen misslyckas så kan man meddela sync failed och ta bort den blinkade actionen, annars så göra man den helfärgad.

Allt för att öka hastigheten när man spelar så att man inte hakar upp sig på tekniska detaljer.

**Comment by melker** [comment]
Om du placerar en worker och det sedan misslyckas. Räcker det med en toast (lilla grå rutan som försvinner automatiskt)?

Den funkar även om man växlar t tex worker-vyn. Fast det ska ju återspeglas även där... man kan få läge då man hat flera actions som pågår samtidigt. .. men det går nog.

**Comment by filwi** [comment]
Toast funkar. Man märker när workern inte finns på kartan längre.

**Comment by melker** [comment]
Det finns ett litet problem med detta....
Säg att du placerar worker lvl 1 på en fontän
Sedan level 3 på samma. Sedan meddelar den att den misslyckades med llv1-placeringen... och lvl3 gick igenom. Då kan du inte placera lvl1...

**Comment by filwi** [comment]
Min tanke är att det inte gör något. Man kommer inte att ragequitta över en sådan sak, men det kan man göra om man måste vänta och vänta mellan varje worker.

**Comment by melker** [comment]
Jag störde mig själv på detta. Nu har jag släppt en första version av det.
0.4.129
Det finns säkert buggar i den....

**Comment by melker** [comment]
Lite fixade buggar som gör att den hanterar t.ex. nätverksfel i 0.4.131

**Comment by melker** [comment]
Fixat en null pointer exception i 0.4.131. Kommer nästa version
Fortsätt skicka in krasher.

**Comment by melker** [comment]
Funkar skapligt. Stänger ärendet och så får ev buggar hanteras efterhand.
