### ISSUE TITLE
Spacing på workers kring fontän

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#73]
Vad sägs om att ha följande sätt att placera workers kring en fontän:

Första workern placeras baserat på en slum genererad från fontänens hash (samma som placering av fontäner).

Resten av workers placeras jämnt runt fontänen (dvs dela med antal workers som är placerade, sedan spaca ut dem).

Alternativt är att man randomiserar lite grand baserat på fontänens hash.

Tanken är att det ska vara lika spacing men att varje fontän ändå får en "egen" och konstant look när man placerar workers på den. Det skapar igenkänning när man spelat ett tag.

**Comment by melker** [comment]
Just nu är en workers vinkel enbart baserat på workerns id, men en del blir
ju väldigt lika.

Att fördela cirkeln jämnt bli lustigt för då kommer en w att flytta på sig
när man placerar nästa. Då behövs i stället fixa pos för första, andra...
fast det blir lustigt när man ta tillbaka en worker....

Kan man baserade det bara på workern själv (med förskjutning baserat på
fontänens id) så står den kvar.

**Comment by filwi** [comment]
Varför inte låta workers flytta på sig? De är som bin, när ett nytt bi kommer så flyttar de andra på sig och släpper in det i cirkeln. Visar på att alla arbetar tillsammans för det allmäna goda, vi kan väva in det i storyn. Och så kommer det att se snyggt ut.

**Comment by melker** [comment]
Det kan de väl få. Jag tänkte mest att man placerar dem och sedan vill man se var ens egna är och att det var lustigt att utplcerade "saker" flyttar på sig.... En annan ide är att för mig så visas mina på en speciell vinkel och andras på annan vinkel

**Comment by filwi** [comment]
Vad sägs om detta: vi spacar dem jämt, med en viss variation baserat på fontänens hash, men att man alltid ser sina egna "först" och att "först innebär i en position som är på/kring toppen av fontänen (uppåt/norrut när man tittar på kartan)?

Dvs. att workers kring en fontän är ordnade på olika sätt för olika användare.

**Comment by melker** [comment]
Ok

**Comment by melker** [comment]
Fixat i 0.4.112.. fast inte att de egna hamnade först insåg jag nu.

**Comment by melker** [comment]
0.4.113 De egna ska visas först. Inte testat men jag utgår från att det blev rätt...
