### ISSUE TITLE
Markera mitten på portal-cirkeln när man sätter ut portal.

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#75]
Som det låter, att man markerar var mitten på portalen är så man inte behöver gissa sig till det.

**Comment by melker** [comment]
En portal hade jag ju tidigare när man placerade ut. Vad ska det vara? Hårkors, prick, genomskinlig portal, annat?

**Comment by filwi** [comment]
Prick, men hyffsat stor. Vi får testa och se hur det ser ut på olika telefoner.

**Comment by melker** [comment]
0.4.115
Jag har nu fixas så den är lite "sticky" vid kanten på hur långt ut den får placeras. Det kanske är tillräckligt och det man egentligen vill ha.

**Comment by melker** [comment]
Kommentar på detta?

**Comment by filwi** [comment]
Det funkar fint, stänger den här.
