### ISSUE TITLE
Ny portal grafik

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#76]
Behöver göras i samma stuk som nya fontänerna.

**Comment by filwi** [comment]
Portaler i alla 5 färgerna, 256 x 256 pixlar. Funkar det?

![portal-blue-v0 2-140821-01](https://cloud.githubusercontent.com/assets/8066290/3997077/ed95eb14-293b-11e4-9425-23ecf03f6768.png)
![portal-green-v0 2-140821-01](https://cloud.githubusercontent.com/assets/8066290/3997075/ed941500-293b-11e4-8f31-9d3d1cd75f0b.png)
![portal-purple-v0 2-140821-01](https://cloud.githubusercontent.com/assets/8066290/3997078/ed96659e-293b-11e4-91c7-885ea02fe646.png)
![portal-red-v0 2-140821-01](https://cloud.githubusercontent.com/assets/8066290/3997076/ed94b21c-293b-11e4-90b3-8b5450030af6.png)
![portal-yellow-v0 2-140821-01](https://cloud.githubusercontent.com/assets/8066290/3997079/ed9c03aa-293b-11e4-9791-24c3f2ed4857.png)

**Comment by melker** [comment]
Fontäner menar du?

**Comment by filwi** [comment]
Nej, portaler, det som man ställer ut för att kunna placera ut workers senare. Kodat till den färg som spelaren har. Inte för att de kommer att se andras portaler men det är ju alltid kul att få sin egen färg bekräftad...

Och nu i rätt storlek också.

**Comment by melker** [comment]
Ok.

**Comment by melker** [comment]
Inlagt
