### ISSUE TITLE
Möjlighet att flytta om worker attribut

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#77]
Borde vi ha en möjlighet att flytta om workerattribut nu när de är så dyra att bygga? Annars är det väldigt vanskligt att förändra om man tvingas bygga nytt hela tiden. Bättre att man kan laborera med de som man har.

Men då är frågan, om man ändrar så att man inte längre kan ha placerat ut workers där de finns, ska de åka hem då? Eller ska vi ignorera det helt och hållet? Jag röstar på åka hem, det blir en kostand (i tid och ansträngning) för att ändra attribut så då behöver det inte finnas kostnader i färg. Vad tror du?

**Comment by melker** [comment]
Eftersom det bara är vid själva utplaceringen som sådant kollas kajag tänka mig att om man ska kunna ändra om så SKA alla workers vara hemma eller skickas hem. Om man ska ändra om så ska det väl kosta lite ändå så man inte gör det hela tiden... eller så kan det vara en del av spelet.  Man ska ju ha mer att göra än att plcera workers... man ska göra det optimalt för där man är.

**Comment by filwi** [comment]
Håller med, ska man ända så åker alla workers hem. Det blir en kostnad i tid/aktivitet.

**Comment by melker** [comment]
Bra ideer för hur det ska grafiskt ska se ut?

För övrigt så kommer "downgrade" att försvinna om vi gör detta.

**Comment by filwi** [comment]
```
Nja, downgrade kan fortfarande behövas eftersom antalet byggda
attribut styr vad nästa kostar. Tänk att man bara bygger capacity
och sedan kommer det någon annan och spelar i ens area - man kan
bygga in sig på ett spår som tar död på spelet. 
Men jag har tänkt en drag-and-drop lista för att flytta om. Vi får
träffas i veckan och rita lite. Förresten, när är du tillbaka på
jobbet?
/FOn 2014-08-08 21:15, Erik Melkersson
  wrote:

  Bra ideer för hur det ska grafiskt ska se ut?
  För övrigt så kommer "downgrade" att försvinna om vi gör detta.
  —
    Reply to this email directly or view
      it on GitHub.

-- 
    Filip Wiltgren
      Freelance Writer & Game Designer

      +46 (0)73-577 45 91 | filip@wiltgren.comWebsite | Blog | LinkedIn
```

**Comment by melker** [comment]
Detta fungerar ju idag.

Det är bara en liten bugg kvar men den lägger jag in separat
