### ISSUE TITLE
Titlar

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#78]
Vad sägs om:

Lead developer: Erik Melkersson
Lead designer: Filip Wiltgren

Det ger intrycket att det finns lite mer krut och kraft bakom spelet, och ser finare ut i resumén senare.

**Comment by filwi** [comment]
Vi skulle kunna dra på lite extra:

Concept: Erik & Filip
Development: Erik
Game design: Filip
Art: Filip (ev, annan)
Testing: Alla våra (icke existerande) betatestare.

**Comment by melker** [comment]
Blir säkert bra.

**Comment by melker** [comment]
Bara tryckte in texten....
