### ISSUE TITLE
Ser inte längre spelaren "Jobb"

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#80]
Jag ser inte längre spelaren Jobb i listan. Det borde jag göra eftersom jag har haft kontakt med den en gång i tiden (enligt vad vi sagt, men det kanske är ändrat).

**Comment by melker** [comment]
Ja...jag vet inte vad som hände med den. Jag tror den har något galet i db

**Comment by melker** [comment]
Släpper detta så länge.
