### ISSUE TITLE
Story: spelaren är basen

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#81]
Vad sägs om följande story: man är en crystalin varelse som skickas till jorden för att farma färg. Så basen är ens egen "kropp" och då får vi följande termer:
- transmute color
- modulate worker (ändra färg)
- extrude worker (bygga worker), alternativt grow worker
- tap crystal (ta färg från fontän)
- grow base

Vad tror du?

**Comment by melker** [comment]
Alternativ tanke: att spelet inleds med nödanrop från "rymdskepp" som inte själva kan komma för nära vår planet men att el.enheten man har kan styra dem....

Men din tanke funkar bra med. Att man får reda på att man är "speciell".

**Comment by filwi** [comment]
Ok, jag tänker vidare och spånar på en text.

**Comment by melker** [comment]
Ersatt at #91
