### ISSUE TITLE
Slå samman color notifications

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#83]
När man ser en notification så ska den slå samman all färg av varje slag som man fått:

i stället för "8 red" och nästa "8 red" så addera ihop dem till "16 red" i stället. Så att man i sin notification får bara max fem färger (en av varje som man fått i) och inte flera av varje färg.

**Comment by melker** [comment]
Medhåll. Trodde jag hade lagt in ticket om det tidigare... eller så var det bara kommentar i min kod.

**Comment by melker** [comment]
Jag har nu bytt till att notifieringen visar hur många idle workers och hur mycket färg man har , sammanlagt.
