### ISSUE TITLE
Bugg i mängden färg från fontäner?

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#85]
Jag har märkt att alla mina workers alltid kommer tillbaka fulladdade från fontäner. Det borde inte vara så om fontänerna slutar leverera när de är slut - och om de inte är slut så borde de inte försvinna när workers kommer tillbaka.

**Comment by melker** [comment]
Kanke är fel.... jag har inte satt så många på samma nu för tiden... behöver testas lite.

**Comment by melker** [comment]
Fixat buggar på sever. Förhoppningsvis är det löst nu.
