### ISSUE TITLE
Halvera fontänantalet

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#87]
Man behöver ju inte flytta på sig så mycket nu.

**Comment by filwi** [comment]
Tror jag gillar "fler workers" bättre än "färre fontäner". Ja, man behöver inte röra på sig så mycket, men det är lite av charmen med spelet. Det är inte ingress eller alla andra GPS-based där man måste kuta runt hela tiden för att spela, i stället kan man spela lite casual och ändå få ut en hel del av det. Jag röstar för att vi behåller det som det är just nu och ser vad som händer när vi har fler spelare som blockerar fontäner.

**Comment by filwi** [comment]
När jag testar med många workers så tömmer man fontänerna runt sina vanliga platser ganska regelbundet. Jag kan kanske sätta ut alla mina workers 1 ggr/vecka utan att åka utanför där jag brukar vara. Annars så är det att leta de 2-3 fontänerna som finns tillgängliga just då, vilket är bra för att man har en anledning att logga in med jämna mellanrum.

Jag föreslår att vi stänger den har issuen och lämnar det till beta-testning med många spelare att utvisa om det behövs någon förändring.

**Comment by melker** [comment]
Medhåll
