### ISSUE TITLE
Minska kostnad för byggnad för fler workers.

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#88]
Jag kan nu komma upp till 5 men sedan är det jobbigt. Några till ska man kunna få...

**Comment by filwi** [comment]
Osäker på detta. Ja, det blir dyrt, men så ska det vara. Man ska behöva åka runt lite och vara aktiv för att kunna dra in många workers.

**Comment by melker** [comment]
Ja... men det som tar tid är ju att vänta på att de ska ladda... några fler tycker jag nog man ska kunna ha så man faktiskt vill åka runt för att besöka dem... fast det kanske #87 löser.... avslår detta så länge då.
