### ISSUE TITLE
Scoring view idéer

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#89]
Lite tankar, vad tror du om:
1. Vi lägger till ytterligare en nivå (har diskutterats tidigare), med en rutstorlek på 2x2 km, sedan nästa nivå på 10x10 sådana rutor, sedan nästa med 20x20 nivå två rutor (dvs 400 x 400 km). Det gör att det lönar sig att åka en bit innan man sätter ut sin scorer och även att byta scorers med folk i andra bigareas (400 x 400 km areorna).
2. Vi skriver in vilken position man har i varje ruta man ser i scoring view (t.ex. X/Y där X är ens egen position och Y är totalt antal i rutan). Sedan kan man scrolla runt och se vilken ruta man vill lägga in sig i. Kanske även skriva in hur många poäng man behöver för att nå nästa bättre postion i rutan. Vi kommer nog behöva ta det här live så vi inte missförstår varandra.
3. I varje ruta visar man namnet på det leadande teamet (förkortning) och den ledande spelaren (teamförkortning + namn). Det skulle ge folk något att kämpa om. Särskilt om man kan se vilka rutor man själv är ledande i (man får en lite snyggare färgad border på rutan eller något), kanske även att man kan klicka på en annan spelare och se deras stats och vilka rutor de leder i.

**Comment by melker** [comment]
Det är en sfär vi pratar om... men om det är ok att rutorna blir mycket
mindre närmare polerna så funkar "rutor".

**Comment by filwi** [comment]
Helt OK - stackarn som sitter ensam på Svalbard och spelar behöver all hjälp hen kan få...

**Comment by melker** [comment]
I versionen som kommer nu finns en nivå till. (fler blir bara grötigt)
Poängen är nollställda nu.

Det är 28 stora rutor i världen varav nord- och sydpolen är de mest lustiga. (ungefär europa är en)
Dessa är indelade i 8x8 rutor (ung södra sverige)
Dessa är i sin tur indelade i 64x64 rutor (små... kanske lite för små... men jag tror det blir bra ur rörelsesynpunkt)

Det är bara de små som ger bonus.
Övriga nivåer ger bara summering och rankinglistor

Hur man ska få bonus av någon långt bort (snarare än grannstaden) blir en senare fråga.... men vi börjar så tycketr jag.

**Comment by filwi** [comment]
Ok, vi får testa och se vad som händer.

**Comment by filwi** [comment]
![scoring view ruta 140819](https://cloud.githubusercontent.com/assets/8066290/3963588/463442b2-277e-11e4-911b-d734db4ff141.png)

Vad tror du?

**Comment by melker** [comment]
Är din tanke på vanl. kartan?

**Comment by filwi** [comment]
Min tanke var på scoring view, att man kan scrolla runt på kartan där och kika. Men om vi har med det på vanliga kartan, och bara har en toggle för att visa scoring, så skulle det vara lättare för spelarna. Vad tror du?

**Comment by melker** [comment]
Hmmm....

Jag nu laddar den bara poängen för de ytor där man faktiskt har tagit poäng
men man skulle kunna ladda efterhand som man på något sätt hoppar till
andra ytor.

Jag vill i alla fall se listan med personer. Kartan var min tanke på att
bara visa var det är och inte som "navigering".
Om vi ska ha den som navigering så kan man ju tänka sig:
     ^   M
< |___| >
     V   +-
Dvs lista listan över själva ytan.
Ha kontroller omkring för att scrolla en ruta i sidled.
+- zoom saker.

Problemet är när man zoomar in. Vilken av de 64x64 ska man hamna i då...

Är du inne på att man växlar på/av att listan med folk visas med knappen
uppe till häger i ditt exempel? och att man navigerar som "vanligt" på
kartan?

**Comment by filwi** [comment]
Jag tänkte att man ska visa listan med personer bara om man vill se den. Tanken med att visa vem som är först i en ruta är att man kan dra samman rutor till områden (grafiskt bara, ingen effekt speltekniskt) och på så sätt få in känslan av "ja! jag kontrollerar halva linköping" (eller "han/hon kontrollerar halva linköping"). Och göra samma sak med teams, att man kan visa en rand för team, en rand för person.

Lista över själva ytan är inte bra, det tar för mycket i anspråk. Om man ska ha något sådant så ska det vara att man klickar på kartan för att få fram en lista för just den (dvs en minikarta i toppen och en lista under).

Vi behöver kanske ta det här live?

**Comment by melker** [comment]
Gillar tanken med "snabbsummering" av de ytor som just nu visas på
skärmen...
Topp 3 i stället för bara en?

Det är för övrigt lite problem med att den räknar exakt fram till nu och
att poängen är live... poängen kan växla ganska mycket varje sekund,
beroende på att gränsen för att ha satt en scorer i en yta under ett viss
dygn hela tiden ändras. Vi bör nog införa en fix tidsperiod så det inte
blir så ustigt.

(Lite live-prat vore nog bra... strax möte här dock, men efter, vid
15:20-tiden? Tänkte sluta då.)

erik.melkersson@gmail.com

**Comment by melker** [comment]
Just det ja:
Egen flik... tror jag (men båda med kartbakgrund)

Ska man skicka scorer i den fliken/mode då i stället eftersom det är där
man ser vilken man är i och vad effekten blir?
Då kan jag dessutom ta bort scorer-rutorna i vanliga vyn. (som är lite
halvdanna och helt fel just nu)

**Comment by filwi** [comment]
Ser för och nackdelar med egen flick, definitivt ta det live men inte idag, möten hela dagen.

**Comment by melker** [comment]
Ska man placera ut scorers där?
Detta behöver vi diskutera juh!

**Comment by melker** [comment]
Diskussion idag:
- Scorers placeras precis som idag.
- Vanliga kartan ska visa scoring-ytorna
- Fliken med scoring försvinner
- Rutan som visar placering uppe till vänster  på kartan ska visa placering i den ruta som är mitt på kartan. 
- Aktuell ruta (dvs den som är mitt på kartan) ska markeras på något sätt så man ser för vilken aktuell position visas.
- Om man klickar på placeringsrutan så ska den skicka upp en dialog med poängen där. Dvs man kan välja mellan lilla, mellan, stora, world och team. (flika, drop down eller vad som nu är enklast och vettigt)
- Poäng som visas i listan i dialogen är toppnoteringarna och de omkring den egna placeringen (dvs om man är långt ner, så man man se hur mycket man måste ta för att avancera)

**Comment by melker** [comment]
Fundering för att göra det enklare och mindre kladdigt.
- Visa BARA den score area som mitten av kartan är i, på lämplig(a) nivå(er).

Borde väl räcka långt?

**Comment by melker** [comment]
Förslag:
- Att visa score-area och rank hänger ihop i inställningen
- När man bygger/skickar(?) sin första scorer ändras den inställningen från av (startläge) till på (med infoo om att så skett)

**Comment by melker** [comment]
0.4.104 
- Inställning för att visa score areas på kartan.
- Visar den aktuella scoring-arean som är mitt i bild.

Min tanke är att det är tillräckligt bra och dessutom prestanda/bloatmässigt bra. Förutom utvecklarmässigt mycket bra. 

Med den anser jag punkten: "Vanliga kartan ska visa scoring-ytorna" löst.

**Comment by melker** [comment]
0.4.105
När man klickar på rank-vyn så får man upp dialog med scoring-lista för just den ytan
(OBS rank-vyn visas fortfarande för där man faktiskt är, inte var kartan är centrerad)

**Comment by melker** [comment]
0.4.106
Nu visar rank.vyn rank i den markerade ytan (dvs mitt på kartan)

**Comment by melker** [comment]
0.4.107
Fliken bortplockad.

Att lista de omkring spelarens rank får bli senare... restpunkt när det blir aktuellt. #130
