### ISSUE TITLE
Story förslag

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#91]
Introskärm:

Seedling, you have survived! Joyous condescension bubbles through my secondary sphincter. The Rubinium shall flow! We shall be awash in Gelbur! Joy, joy, joy, four times resounding joy!
Do you like my mode of speech? We have taken special steps to sound like your adopted host species in this recording.
But enough with the biological entity noises. Moviridien makes the world go circular! It is time to rouse you dues so we may grow rich and famous together!
You have spawned on a rare world indeed, awash in all five of the primary crystals. You must harvest the crystals, bring back the five energy colors and transmit them through the ether to our home world. But first, the naming ceremony:

Choose your alias: ____________

**Comment by melker** [comment]
Inlagt.
