### ISSUE TITLE
Bug i GPS

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#92]
0.4.74 (och tidigare version också) startar inte GPS längre. Den tar bara positionen från närmsta wifi eller torn (dvs A-GPS delen verkar funka men inte själva GPS). Går att återskapa utan problem - händer varje gång.

**Comment by melker** [comment]
Fixat i 0.4.76, som kommer.

Jag hade någon gång sänkt ACCURACY på positionering för att kunna testa snabbare när jag grejade med något...
