### ISSUE TITLE
Uppdaterar inte skärmen när man loggar in

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#93]
Informationen när man loggar in uppdateras inte, man ser gamla kartan ända tills man går till workers vyn, därefter ser jag ny, uppdaterad karta och uppdaterade workers på kartvyn. v0.4.74

**Comment by melker** [comment]
Fråga: Är det när du haft den igång. Sedan gjort något annat. Vänntat en tid och sedan startar appen på nytt. Eller vad är den "gamla"?

**Comment by filwi** [comment]
Svårt att återskapa. Verkar vara i samma typer av fall som när jag inte ser någon karta alls.

**Comment by melker** [comment]
Borde funka nu. 0.4.168

**Comment by melker** [comment]
Äh, jag stänger. Är inte riktigt likadant längre.
