### ISSUE TITLE
Större avstånd i byta färg UI

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#94]
Det är för lätt att trycka på linjen när man trycker på + tecknen. Öka avståndet mellan + och linjen, alternativt lägg de bredvid ikonen (kanske bättre, i så fall: -10, -1, ikon för nya färgen, +1, +10).

**Comment by melker** [comment]
Justerat lite i 0.4.82. Bara ökat avstånd. Kolla att ok.

**Comment by filwi** [comment]
Ser OK ut.
