### ISSUE TITLE
Othercount ska täcka 2 workers

### ISSUE THREAD

**Issue by filwi** [melker/colorplanet#96]
Othercount behöver boostas, jag ser redan att det kommer att bli för kasst att investera i det om man bara täcker in en fientlig worker, speciellt om vi lägger samman alla fientliga workers kring en fontän, inte bara den som har flest.

Mitt förslag:

Man börjar med 1 level i othercount (som nu).
Varje level gör att man kan ställa ut även om det är 2 workers där (så har man lvl 3 så kan man ställa ut även med 6 fientliga workers på en fontän).
Alla workers slåss samman (dvs man räknar alla andra spelare workers på den fontänen, inte bara en spelares).

**Comment by melker** [comment]
Ok

**Comment by melker** [comment]
Fixat på server. Kräver dock att du gör en upgrade eller downgrade på Worker Upgrader för att applicera på bef workers.
