### ISSUE TITLE
Förslag: Flytta saker från facility-fliken till det de hör samman med, och rundflyttning i menyer...

### ISSUE THREAD

**Issue by melker** [melker/colorplanet#97]
T.ex. producer/upgrader (som vi ju grafisk slagit samman) och ändra-färg saken läggs övers på workers-fliken och skapa ny worker knappen läggs vid  producer/upgrader.

Scorer part-omvandlaren och ny byggnad för mängd sam sammanslagning läggs överst på scorerpart-fliken. 

Placera scorer hamnar på score(r)-flik tillsammans med vis poäng.

Kvar att fundera på är transmitter-sak men den kanske ska få en egen flik, om man ha "slots" för vad man kan ta emot som man aktivt måste tömma. (uppgraderingsmöjlighet)

Portalbyggnad kanske ska läggas på första, Longpress på portal-saken? (Kans vara svårt att hitta första gången)

Mer tankar:
Worker producer/upgrader - klick => skapa worker, lockclick gå in i dess meny för att redigera nivåer etc. Men skapa worker kan finnas även där. Så frigör man yta.

Vad säger du?

**Comment by filwi** [comment]
Vi behöver ta det här live, lite mer komplext än det verkar; rör egentligen hela UI och spelkänslan.

Vad sägs om måndag? Jag ska prata med Cajsa efter lunch, ska vi ta ett snack omkring då?

**Comment by melker** [comment]
Vi kan försöka måndag. Konsulterna börjar så vi får se hur det är...

**Comment by melker** [comment]
Avslag.
